// app/lib/errorCodes.js - Complete ATM Error Code Database (Genmega + Hyosung)

export const errorCodes = [
  // ==================== GENMEGA ====================
  { code: "0", brand: "Genmega", description: "Normal Status", resolution: "None" },
  { code: "CDN04", brand: "Genmega", description: "CDU Connection Failure", resolution: "Check cables between CDU and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. This error is of concern only if repeated. Outside interference may cause it (neon signs, lights)." },
  { code: "D1704", brand: "Genmega", description: "Modem connection error", resolution: "Phone line will not support data communication. In-line filter may help. Excessive EMI emissions from outside source (neon sign, freezer) are likely causes. Check all programming (especially Dual Master Key setting and Host Processor Mode)." },
  { code: "20001", brand: "Genmega", description: "Unable To Detect Cassette", resolution: "Remove and replace cassette. Check the micro-switch on the inside left wall of the dispenser. Adjust if needed. Check the white plastic clips that hold the cassette in place — if broken the cassette will not stay in the dispenser." },
  { code: "20002", brand: "Genmega", description: "Low Cash", resolution: "Low cash warning sensor is open. When 'Low Cash Warning' is enabled, this sensor opens when the cassette reaches (~75 bills). If typically stocked with low bills, consider disabling this function." },
  { code: "20003", brand: "Genmega", description: "Reject Bin is Full", resolution: "Empty reject bin. If bin is empty, do a Cassette Total from the settlement menu. If that doesn't help, check that AP, BIOS and CDU ROM versions are compatible." },
  { code: "20004", brand: "Genmega", description: "Vault Door is Open", resolution: "Check vault door switch (white plunger switch in upper left corner of vault). Check that the black and white 2-wire connector is properly connected at rear of main board. Move the vault switch forward to aid door clearance. Check for continuity between the switch and mainboard connector." },
  { code: "20005", brand: "Genmega", description: "CDU Type Mismatch", resolution: "CDU ROM does not match AP software. The dispenser and mainboard must share the same country code (USA or Canada). If they don't match, reprogram the CDU. Also check if wrong parameters were entered when the CDU was programmed." },
  { code: "20010", brand: "Genmega", description: "Receipt Paper Jam", resolution: "Remove jammed paper. Release receipt paper drawer by pressing the tab with the green sticker at the front of the printer. You may have to remove the printer to locate difficult jams. Do NOT use metal objects — use a business card or stiff paper. Use only 21# paper." },
  { code: "20012", brand: "Genmega", description: "Receipt printer feed lever open", resolution: "Close the feed tray on the printer. If already closed, try opening and closing it, try the printer reset switch. Otherwise the printer may require service." },
  { code: "20013", brand: "Genmega", description: "Receipt paper is empty", resolution: "Replenish the paper roll. If paper is already in the printer, look for jams or obstructions. Try the printer reset switch. If error persists, the printer may require service." },
  { code: "20014", brand: "Genmega", description: "Thermal printer is overheated", resolution: "Allow the printer to cool and try again. Try the reset button on the printer. If this error persists, the printer will require service." },
  { code: "20215", brand: "Genmega", description: "CDU detects bills prior to dispensing (CS2 sensor)", resolution: "Remove any jammed bills from the dispenser. If no bills are present, use compressed air to clean the dispenser (a sensor may be blocked by dust). Check and reseat all belts — loose belts can slip off rollers and block sensors." },
  { code: "21315", brand: "Genmega", description: "CDU detects bills prior to dispensing (CS13 sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "21A15", brand: "Genmega", description: "CDU detects bills prior to dispensing (CS1A sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "21B15", brand: "Genmega", description: "CDU detects bills prior to dispensing (CS1B sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "24A15", brand: "Genmega", description: "CDU detects bills prior to dispensing (CS4A sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "24B15", brand: "Genmega", description: "CDU detects bills prior to dispensing (CS4B sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "90001", brand: "Genmega", description: "Error during card swipe", resolution: "Occurs when customer attempts to swipe card unsuccessfully. May indicate card reader needs cleaning, repositioning, or the customer didn't swipe properly. If persistent, clean and test the card reader in diagnostics. Very common — does not usually indicate a bad part." },
  { code: "A0008", brand: "Genmega", description: "Receipt paper cutter error", resolution: "Remove any jammed paper. You may need to remove the printer to clear jams. Do not use metal objects — use a business card or stiff paper. Try the reset button or have the printer serviced." },
  { code: "ADN04", brand: "Genmega", description: "Printer connection error", resolution: "Check cables between Printer and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Try the reset button on the printer. If consistent, the printer or mainboard may require service." },
  { code: "ADN0F", brand: "Genmega", description: "Printer connection error", resolution: "Check cables between Printer and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Try the reset button. If consistent, printer or mainboard may require service." },
  { code: "ADNxx", brand: "Genmega", description: "Printer connection error", resolution: "Check cables between Printer and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Try the reset button. If consistent, printer or mainboard may require service." },
  { code: "Axxx2", brand: "Genmega", description: "Thermal printer overheated during operation", resolution: "Allow the printer to cool and try again. Try the reset button. If this error persists, the printer will require service." },
  { code: "Axxx3", brand: "Genmega", description: "Receipt Paper Jam", resolution: "Remove jammed paper. Release receipt paper drawer by pressing the tab with the green sticker. You may need to remove the printer from the ATM to access the jam. Do NOT use metal objects." },
  { code: "Axxx4", brand: "Genmega", description: "Receipt paper is empty", resolution: "Replenish the paper roll. If roll is ok, try the reset button. Otherwise the printer needs service." },
  { code: "Axxx5", brand: "Genmega", description: "Receipt paper jamming during loading", resolution: "Remove any jammed paper and reload. You may need to remove the printer to clear jams. Do not use metal objects. Try the reset button or have the printer serviced." },
  { code: "C0011", brand: "Genmega", description: "CDU sensor is tripped", resolution: "During dispense, the sensor at the front of the CDU shows a blockage (CS13 or CS2). Usually a bill bouncing back from the cash tray. Check the front of the CDU and cash tray for blockage. Reinitialize the ATM to put back in service." },
  { code: "C0014", brand: "Genmega", description: "CDU sensor is tripped", resolution: "Similar to C0011 — indicates a bill jam close to the exit of the CDU or near the reject bin. Check for jammed notes or blocked sensors." },
  { code: "C001x", brand: "Genmega", description: "CDU sensor is tripped", resolution: "Typically a C0011 error — bill jam at the exit sensor of the Cash Dispenser. Usually caused by a customer putting fingers in the cash drawer during dispense. You can loosen the screws that hold the dispenser and slide it back." },
  { code: "C0028", brand: "Genmega", description: "CDU sensor is tripped", resolution: "Check dispenser for jammed bills and restart the machine. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C002x", brand: "Genmega", description: "CDU sensor is tripped", resolution: "Check dispenser for jammed bills and restart the machine. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0030", brand: "Genmega", description: "CDU motor failure", resolution: "Motor speed (measured at the encoder wheel) was not within spec. Verify that CS8 or encoder wheel sensor is in place and wire connection is good. Can indicate a bad motor or encoder sensor." },
  { code: "C0031", brand: "Genmega", description: "CDU Gate solenoid error", resolution: "The CDU did not respond to its solenoid function check. Check the wiring connections to the solenoid(s) and to the CDU main board." },
  { code: "C0032", brand: "Genmega", description: "Outlet solenoid error", resolution: "Check and verify all connections to the dispenser circuit board. Check wiring to the solenoid(s)." },
  { code: "C0033", brand: "Genmega", description: "CDU Encoder error", resolution: "Usually caused by loss of battery power to the CDU mainboard. The only way to recover is to reprogram the CDU data. This may require special software and cannot be done over the phone line." },
  { code: "C0034", brand: "Genmega", description: "Double Note detect module failure", resolution: "Double detect module reporting error. Check wiring to the module." },
  { code: "C0035", brand: "Genmega", description: "Double Note detect module failure (2)", resolution: "Double detect module reporting error. Check wiring to the module." },
  { code: "C0036", brand: "Genmega", description: "Detected notes in path before initializing", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0037", brand: "Genmega", description: "Sensor for detecting Double covered during dispensing", resolution: "None" },
  { code: "C0039", brand: "Genmega", description: "Gate sensor open during initializing", resolution: "Check the sensor activated when you close the reject bin door (2k/4k dispensers only). Check the springs on the underside of the solenoids — one may be disconnected. Otherwise the CDU will require repair/replacement." },
  { code: "C003B", brand: "Genmega", description: "Notes detected during installation", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0040", brand: "Genmega", description: "Cassette removed during dispense", resolution: "Reset the cassette. Check position of microswitch on right rear wall of cassette bay in the dispenser. Check the condition of the white plastic cassette retaining clips." },
  { code: "C0041", brand: "Genmega", description: "Tried to dispense notes more than 5 times", resolution: "Check the condition of the cash in the cassette. Verify cash is of good quality. The CDU belts or cassette rollers may need to be cleaned (rubbing alcohol). Check that the denomination in Transaction Setup matches the actual denomination loaded." },
  { code: "C0042", brand: "Genmega", description: "Note jam", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0043", brand: "Genmega", description: "More than 10 notes rejected during one transaction", resolution: "Verify the quality of the cash. Straighten and shuffle cash in the cassette. Check the reject analysis (reports menu). If cash is good quality, try cleaning the cassette and dispenser. Otherwise service may be required." },
  { code: "C0044", brand: "Genmega", description: "More than 5 notes rejected consecutively", resolution: "Verify the quality of the cash. Straighten and shuffle cash in the cassette. Check the reject analysis (reports menu). If cash is good quality, try cleaning. Otherwise service may be required." },
  { code: "C0045", brand: "Genmega", description: "Notes Overdispensed", resolution: "Check NS4 Sensor." },
  { code: "C0046", brand: "Genmega", description: "CDU Hardware Failure", resolution: "Error reported during CDU initialization. Check cabling and potential blockages and power cycle ATM." },
  { code: "C0047", brand: "Genmega", description: "Feed error", resolution: "Dispenser attempts to pull a bill from the cassette and is unsuccessful before timing out. Can be as simple as the cassette being empty, rollers needing cleaning, or a firmware upgrade to the CDU may be needed." },
  { code: "C0048", brand: "Genmega", description: "Incorrect bill count", resolution: "Verify cash count in the Settlement menu." },
  { code: "C004A", brand: "Genmega", description: "Jammed notes", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C004B", brand: "Genmega", description: "Long note detected 3 times consecutively", resolution: "Verify the quality of the cash. Straighten and shuffle cash in the cassette. Try cleaning the cassette and dispenser. If persistent, service may be required." },
  { code: "C004C", brand: "Genmega", description: "Miscount of notes between sensors", resolution: "Verify operation of exit gate. Check the number of dispensed notes. Clean the dispenser and test using diagnostics. Dispenser may require service." },
  { code: "C004D", brand: "Genmega", description: "Cash cassette not properly set", resolution: "Reset the cassette. Check position of microswitch on right rear wall of cassette bay. Check condition of white plastic cassette retaining clips. MB1000: check condition of the clutch alignment screw." },
  { code: "C004E", brand: "Genmega", description: "Miscount of notes between sensors", resolution: "Test CDU using diagnostics. Use journal to verify amount of dispensed notes versus requested notes. Clean dispenser and cassette. If error persists, dispenser may require service." },
  { code: "C004F", brand: "Genmega", description: "Miscount of notes between sensors", resolution: "Test CDU using diagnostics. Use journal to verify dispensed notes vs requested. Clean dispenser and cassette. If error persists, dispenser may require service." },
  { code: "C0050", brand: "Genmega", description: "Power failure during dispense", resolution: "Remove any notes from path. Before reinitializing, verify amount of dispensed notes in the cassette against the journal." },
  { code: "C0051", brand: "Genmega", description: "Over 150 notes requested", resolution: "Possibly due to too many rejects. Check the Reject Analysis. Cash quality and condition of rollers in the cassette can affect this condition." },
  { code: "C0052", brand: "Genmega", description: "Detected notes in path after dispense", resolution: "Remove any notes from path. Verify amount of dispensed notes. Clean dispenser. Verify bill count against the journal." },
  { code: "C0053", brand: "Genmega", description: "CDU double detect module failure", resolution: "Double detect module may require adjustment. Check wiring and CDU mainboard connections." },
  { code: "C0055", brand: "Genmega", description: "Detected long notes at outlet sensor", resolution: "Typically a bounce back of a bill during dispense causing the exit sensor to remain blocked longer than expected. See C0011." },
  { code: "C0056", brand: "Genmega", description: "Exit gate sensor failure", resolution: "Check condition of exit gate and the exit gate sensor." },
  { code: "C0057", brand: "Genmega", description: "Cassette information is not properly set", resolution: "CDU programming is not accurate or complete." },
  { code: "C0059", brand: "Genmega", description: "Cash cassette 2 removed prior to dispense", resolution: "Set the cash cassette. Inspect the cassette detection microswitch. Reposition if necessary." },
  { code: "C005A", brand: "Genmega", description: "Cash cassette 1 removed prior to dispense", resolution: "Set the cash cassette. Inspect the cassette detection microswitch. Reposition if necessary." },
  { code: "C005B", brand: "Genmega", description: "Cash cassette 2 misfeed", resolution: "Check cassette for jams. Check condition of bills in cassette." },
  { code: "C005D", brand: "Genmega", description: "Double detect constantly", resolution: "Inspect double detect module and adjust as necessary. Check and clean the cassette and rollers. Verify quality of cash." },
  { code: "C005E", brand: "Genmega", description: "Dispense command size check error", resolution: "Re-initialize machine, verify connections to mainboard. Check for unplugged sensors." },
  { code: "C005F", brand: "Genmega", description: "Dispense command error", resolution: "Re-initialize machine, verify connections, check for unplugged sensors." },
  { code: "C006x", brand: "Genmega", description: "Sensor failure", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C007x", brand: "Genmega", description: "Sensor failure", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0082", brand: "Genmega", description: "Shutter failure", resolution: "Check all wiring connections to CDU mainboard. Reinitialize CDU." },
  { code: "C0083", brand: "Genmega", description: "Stacker sensor failure", resolution: "Check all wiring connections to CDU mainboard. Reinitialize CDU." },
  { code: "C0084", brand: "Genmega", description: "Shutter close error", resolution: "Check all wiring connections to CDU mainboard. Reinitialize CDU." },
  { code: "C009F", brand: "Genmega", description: "Cassette misfeed error", resolution: "Check if notes are available in cassette." },
  { code: "C00AB", brand: "Genmega", description: "Notes detected before initializing", resolution: "Clear notes from dispenser. Possibly dust or foreign object blocking sensor." },
  { code: "C00C7", brand: "Genmega", description: "CS12 Sensor blocked", resolution: "MB2100T: The CS12 sensor at the upper part of the cash tray was blocked while dispensing or initializing. Clear the cash tray of any bills or foreign objects. If error persists, the vault assembly may need to be removed to inspect the sensors." },
  { code: "C00C8", brand: "Genmega", description: "CS14 Sensor blocked", resolution: "MB2100T: The CS14 sensor close to the front of the cash tray was blocked. Clear the cash tray of any bills or foreign objects. If error persists, the vault assembly may need to be removed." },
  { code: "C00C9", brand: "Genmega", description: "CS12 & CS14 Sensors blocked", resolution: "MB2100T: Both CS12 and CS14 sensors were blocked. These sensors prevent tampering with the bill path. Clear the cash tray of any bills or foreign objects. If error persists, the vault assembly may need to be removed." },
  { code: "C00D0", brand: "Genmega", description: "Sensor block while dispensing", resolution: "MB2100T: A blockage was detected between the CS13 (CDU exit gate) and CS12 cash tray sensors. There may be a note stuck in the upper part of the cash tray ramp. Clear the cash tray of notes or foreign objects. Open the vault and slide the dispenser back to access the exit gate area." },
  { code: "C00D1", brand: "Genmega", description: "Sensor blocked while dispensing", resolution: "MB2100T: A blockage was detected between the CS12 (upper cash tray sensor) and CS14 (lower cash tray sensor). There may be a note stuck in the cash tray ramp. Clear the cash tray of notes or foreign objects." },
  { code: "C00E0", brand: "Genmega", description: "NS2A, NS2B dark", resolution: "Nanocash only — verify connections to sensors. Check wiring to mainboard." },
  { code: "C00E1", brand: "Genmega", description: "NS4 dark", resolution: "Verify connections to NS4 sensor. Check all wiring to mainboard." },
  { code: "C00FF", brand: "Genmega", description: "Sensor blocked", resolution: "None" },
  { code: "CANCE", brand: "Genmega", description: "User canceled transaction at surcharge", resolution: "Not an error — a statistic showing how many users respond 'no' to the surcharge notification." },
  { code: "CDN01", brand: "Genmega", description: "No Response after send command", resolution: "None" },
  { code: "CDN05", brand: "Genmega", description: "CDU connection failure", resolution: "Check cables between CDU and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Only a concern if repeated. Outside interference may cause it (neon signs, lights)." },
  { code: "CDN0F", brand: "Genmega", description: "CDU connection failure", resolution: "Check cables between CDU and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Only a concern if repeated." },
  { code: "CDN11", brand: "Genmega", description: "No Response after 3 retry of command", resolution: "None" },
  { code: "CDN12", brand: "Genmega", description: "No Response between ENQ-ACK after 5 retry of ENQ", resolution: "None" },
  { code: "CDN13", brand: "Genmega", description: "No Response after 5 retry due to timeout", resolution: "None" },
  { code: "CDNxx", brand: "Genmega", description: "CDU connection failure", resolution: "Check cables between CDU and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Only a concern if repeated." },
  { code: "D0001", brand: "Genmega", description: "Modem initialization error", resolution: "Check modem in diagnostics or modem test. If persistent, could be a defective modem. One or two instances does not usually indicate a defective part." },
  { code: "D0002", brand: "Genmega", description: "Reversal transaction failed", resolution: "The ATM attempted to do a reversal and could not. Check transaction with the processor. Verify CDU functionality with diagnostics. Verify phone connection. Look in error summary for D1800, D2000." },
  { code: "D0005", brand: "Genmega", description: "Undefined network processing error", resolution: "Code reported by host processor. Contact your ISO or processor if you encounter an excessive amount of these errors or cannot complete a test transaction." },
  { code: "D0011", brand: "Genmega", description: "Format error in the message", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0012", brand: "Genmega", description: "Invalid Transaction", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0013", brand: "Genmega", description: "Invalid Amount", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0014", brand: "Genmega", description: "Invalid Card Number", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0019", brand: "Genmega", description: "Reenter the entire transaction", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0020", brand: "Genmega", description: "Surcharge screen should have been displayed", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0024", brand: "Genmega", description: "Exceeds issuer withdrawal limit", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0031", brand: "Genmega", description: "Issuer financial institution not supported by processor", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0039", brand: "Genmega", description: "No credit account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0041", brand: "Genmega", description: "No credit account found for the CCN", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0043", brand: "Genmega", description: "Stolen Card", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0050", brand: "Genmega", description: "Transaction is not approved", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0051", brand: "Genmega", description: "Insufficient funds", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0052", brand: "Genmega", description: "No checking account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0053", brand: "Genmega", description: "No savings account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0054", brand: "Genmega", description: "Expired Card", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0055", brand: "Genmega", description: "Invalid PIN", resolution: "Code reported from host processor. Verify all programming. For new installations, if master keys are not bound properly or Terminal ID is not active, this can occur. If programming appears correct, contact the processor and have them trace the Terminal ID." },
  { code: "D0056", brand: "Genmega", description: "No card record found", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0057", brand: "Genmega", description: "Transaction not permitted – card", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0058", brand: "Genmega", description: "Transaction not permitted – Terminal", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0059", brand: "Genmega", description: "Customer should contact financial institution", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0060", brand: "Genmega", description: "Allowable withdrawal limit exceeded", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0061", brand: "Genmega", description: "Exceeded withdrawal limit", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0065", brand: "Genmega", description: "Exceeds withdrawal frequency limit", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0067", brand: "Genmega", description: "Capture card at the terminal", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0075", brand: "Genmega", description: "Number of PIN tries exceeded", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0078", brand: "Genmega", description: "No Account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0080", brand: "Genmega", description: "Invalid Date", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0081", brand: "Genmega", description: "Timeout: response not received in time allowed", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0082", brand: "Genmega", description: "Cashback limit exceeded", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0083", brand: "Genmega", description: "Cannot verify PIN", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0084", brand: "Genmega", description: "Processor not available", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0086", brand: "Genmega", description: "Cannot verify PIN", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0090", brand: "Genmega", description: "Cutoff complete for terminal", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0091", brand: "Genmega", description: "Bank unavailable", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0092", brand: "Genmega", description: "System unavailable", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0093", brand: "Genmega", description: "Transaction serial number mismatch", resolution: "Verify all programming, contact host processor." },
  { code: "D0094", brand: "Genmega", description: "Record format mismatch", resolution: "Verify all programming, contact host processor." },
  { code: "D0095", brand: "Genmega", description: "Routing ID mismatch", resolution: "Verify Routing ID number, contact host processor." },
  { code: "D0096", brand: "Genmega", description: "Terminal ID mismatch", resolution: "Verify Terminal ID number, contact host processor." },
  { code: "D0097", brand: "Genmega", description: "Response type mismatch (reversal)", resolution: "Verify all programming, contact host processor." },
  { code: "D0098", brand: "Genmega", description: "Response type mismatch (day-close)", resolution: "Verify all programming, contact host processor." },
  { code: "D0099", brand: "Genmega", description: "Response type mismatch (Configuration)", resolution: "Verify all programming, contact host processor." },
  { code: "D009A", brand: "Genmega", description: "Response type mismatch (Withdrawal, Balance, Transfer)", resolution: "Verify all programming, contact host processor." },
  { code: "D009B", brand: "Genmega", description: "STX omitted", resolution: "Verify all programming, contact host processor." },
  { code: "D009C", brand: "Genmega", description: "ETX omitted", resolution: "Verify all programming, contact host processor." },
  { code: "D009D", brand: "Genmega", description: "FS omitted (after response code)", resolution: "Verify Mini-Bank Software version matches host processor. Contact host processor." },
  { code: "D009E", brand: "Genmega", description: "FS omitted (after retrieval reference number)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D009F", brand: "Genmega", description: "FS omitted (after system trace audit number)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A0", brand: "Genmega", description: "FS omitted (after account balance)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A1", brand: "Genmega", description: "FS omitted (after available balance)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A2", brand: "Genmega", description: "FS omitted (after available balance)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor. Check T-DES Type." },
  { code: "D00A3", brand: "Genmega", description: "FS omitted (after authorization response text)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A4", brand: "Genmega", description: "ETX is in wrong place", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A5", brand: "Genmega", description: "FS omitted (after total cash dispense amount in day close)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A6", brand: "Genmega", description: "FS omitted (after total non cash dispense amount in day close)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A7", brand: "Genmega", description: "FS omitted (after surcharge amount in day close message)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A8", brand: "Genmega", description: "FS omitted (after surcharge amount in configuration message)", resolution: "Verify all programming. Check that Dual Master Key is disabled (non Coredata). Contact host processor." },
  { code: "D00A9", brand: "Genmega", description: "ETX omitted (from configuration message)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00B0", brand: "Genmega", description: "Invalid Terminal ID", resolution: "Contact host processor." },
  { code: "D0100", brand: "Genmega", description: "Transaction approved", resolution: "None" },
  { code: "D0101", brand: "Genmega", description: "Expired card", resolution: "None" },
  { code: "D0102", brand: "Genmega", description: "Unauthorized usage", resolution: "None" },
  { code: "D0103", brand: "Genmega", description: "PIN error", resolution: "None" },
  { code: "D0104", brand: "Genmega", description: "Invalid PIN", resolution: "None" },
  { code: "D0105", brand: "Genmega", description: "Bank unavailable", resolution: "None" },
  { code: "D0106", brand: "Genmega", description: "Card not supported", resolution: "None" },
  { code: "D0107", brand: "Genmega", description: "Insufficient funds", resolution: "None" },
  { code: "D0108", brand: "Genmega", description: "Ineligible transaction", resolution: "None" },
  { code: "D0109", brand: "Genmega", description: "Ineligible account", resolution: "None" },
  { code: "D0110", brand: "Genmega", description: "Number of daily withdrawals exceeded", resolution: "None" },
  { code: "D0111", brand: "Genmega", description: "Cannot process transaction", resolution: "None" },
  { code: "D0112", brand: "Genmega", description: "Amount too large", resolution: "None" },
  { code: "D0113", brand: "Genmega", description: "Account closed", resolution: "None" },
  { code: "D0114", brand: "Genmega", description: "PIN tries exceeded", resolution: "None" },
  { code: "D0115", brand: "Genmega", description: "Database problem", resolution: "None" },
  { code: "D0116", brand: "Genmega", description: "Withdrawal limit already reached", resolution: "None" },
  { code: "D0117", brand: "Genmega", description: "Invalid amount", resolution: "None" },
  { code: "D0118", brand: "Genmega", description: "External decline", resolution: "None" },
  { code: "D0119", brand: "Genmega", description: "System error", resolution: "None" },
  { code: "D0120", brand: "Genmega", description: "Contact card issuer", resolution: "None" },
  { code: "D0121", brand: "Genmega", description: "Routing lookup problem", resolution: "None" },
  { code: "D0122", brand: "Genmega", description: "Message edit error", resolution: "None" },
  { code: "D0123", brand: "Genmega", description: "Transaction not supported", resolution: "None" },
  { code: "D0124", brand: "Genmega", description: "Insufficient funds", resolution: "None" },
  { code: "D0125", brand: "Genmega", description: "Western Union sender data error", resolution: "None" },
  { code: "D0126", brand: "Genmega", description: "Western Union receiver data error", resolution: "None" },
  { code: "D0127", brand: "Genmega", description: "CRC error", resolution: "None" },
  { code: "D0128", brand: "Genmega", description: "Pre-pay transaction failed", resolution: "None" },
  { code: "D0129", brand: "Genmega", description: "Pre-pay transaction rejected", resolution: "None" },
  { code: "D0130", brand: "Genmega", description: "Invalid mobile phone number", resolution: "None" },
  { code: "D0131", brand: "Genmega", description: "Pre-pay account limit reached", resolution: "None" },
  { code: "D0132", brand: "Genmega", description: "Pre-pay system unavailable", resolution: "None" },
  { code: "D0133", brand: "Genmega", description: "Response would exceed message size limit", resolution: "None" },
  { code: "D0134", brand: "Genmega", description: "Necessary information missing to process transaction", resolution: "None" },
  { code: "D0135", brand: "Genmega", description: "Second Invalid PIN (one try left before deactivation)", resolution: "None" },
  { code: "D0300", brand: "Genmega", description: "Modem is not responding", resolution: "Use diagnostic or modem test to test modem. If error is persistent, modem may be defective." },
  { code: "D1000", brand: "Genmega", description: "No Connection", resolution: "Use diagnostic or modem test to test modem. If error is persistent, modem may be defective." },
  { code: "D1100", brand: "Genmega", description: "ENQ not received from host", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D1200", brand: "Genmega", description: "Transmission error", resolution: "Use diagnostic or modem test to test modem. If error is persistent, modem may be defective." },
  { code: "D1300", brand: "Genmega", description: "NAK sent 3 times to host", resolution: "Verify host phone number. If persistent, it could be a defective modem." },
  { code: "D1500", brand: "Genmega", description: "Modem connection timeout – host not responding", resolution: "Verify host phone number and modem speed. If consistent, it can be a defective modem." },
  { code: "D1702", brand: "Genmega", description: "Modem connection error", resolution: "Phone line will not support data communication. In-line filter may help. Check for excessive EMI from outside sources (neon sign, freezer). Check all programming (especially Dual Master Key setting and Host Processor Mode)." },
  { code: "D1706", brand: "Genmega", description: "Modem connection error", resolution: "Phone line will not support data communication. In-line filter may help. Check for excessive EMI from outside sources (neon sign, freezer). Check all programming." },
  { code: "D170x", brand: "Genmega", description: "Modem cannot support connection – excessive line noise", resolution: "Phone line will not support data communication. In-line filter may fix this. Check for excessive EMI from outside sources. Check all programming (especially Dual Master Key setting and Host Processor Mode)." },
  { code: "D1800", brand: "Genmega", description: "No dial tone", resolution: "Verify that incoming phone line is plugged into 'Line' rather than 'Phone' on mainboard. Phone line may be in use or shared with another device (FAX, POS, phone). This error occurs only if there is no dial tone at the mainboard." },
  { code: "D1900", brand: "Genmega", description: "No answer", resolution: "Verify host phone number. There is no answer from the host modem." },
  { code: "D2000", brand: "Genmega", description: "Phone line Busy", resolution: "Verify host phone number — call line with handset and check for busy signal. ATM modem is receiving a busy signal when it dials out." },
  { code: "D2100", brand: "Genmega", description: "Modem initialization error", resolution: "Check modem in diagnostics or modem test. If persistent, could be a defective modem. One or two instances does not usually indicate a defective part." },
  { code: "D2200", brand: "Genmega", description: "EOT not received from host", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D2500", brand: "Genmega", description: "Cannot connect to the host", resolution: "Check the connection." },
  { code: "D2510", brand: "Genmega", description: "Timeout while Sending", resolution: "None" },
  { code: "D2511", brand: "Genmega", description: "Communication error while Sending", resolution: "None" },
  { code: "D2513", brand: "Genmega", description: "Timeout while Receiving", resolution: "None" },
  { code: "D2514", brand: "Genmega", description: "Communication error while Receiving", resolution: "None" },
  { code: "D2515", brand: "Genmega", description: "Socket Error while Receiving", resolution: "None" },
  { code: "D3204", brand: "Genmega", description: "Invalid Host phone number", resolution: "Verify the Host phone number is programmed correctly. Do not use spaces or dashes in the phone number string." },
  { code: "E000x", brand: "Genmega", description: "RMS port failure / response timeout / modem failure / no dial tone", resolution: "Verify RMS settings (Host Setup)." },
  { code: "F0001", brand: "Genmega", description: "Current Number of Bills is 0", resolution: "Load notes into the cash cassette — use Add Cassette function in Settlement." },
  { code: "F0002", brand: "Genmega", description: "No Surcharge Owner set", resolution: "Set Surcharge owner (Customer Setup)." },
  { code: "F0003", brand: "Genmega", description: "No Surcharge Amount", resolution: "Set Surcharge amount (Customer Setup)." },
  { code: "F0004", brand: "Genmega", description: "No refresh timer set when advertisement is enabled", resolution: "Set refresh timer (Customer Setup)." },
  { code: "F0005", brand: "Genmega", description: "No Advertisement text when advertisement is enabled", resolution: "Set Advertisement text (Customer Setup)." },
  { code: "F0006", brand: "Genmega", description: "Dispense limit set error (must be less than 25 notes)", resolution: "Set Dispense limit (Transaction Setup)." },
  { code: "F0007", brand: "Genmega", description: "Denomination Set error", resolution: "Valid Denominations are $10, $20, $50, $100 (Transaction Setup)." },
  { code: "F0008", brand: "Genmega", description: "Fast Cash Set error (cannot exceed dispense limit)", resolution: "Check fast cash settings (Transaction Setup)." },
  { code: "F0009", brand: "Genmega", description: "Master Key index is invalid", resolution: "Check Master Key index — verify checksum (Host Setup)." },
  { code: "F000A", brand: "Genmega", description: "Master Key is empty", resolution: "Check Master Key checksum — reinject key (Host Setup)." },
  { code: "F000B", brand: "Genmega", description: "Host Telephone Number is not set", resolution: "Set Host Telephone Number (Host Setup)." },
  { code: "F000C", brand: "Genmega", description: "Error Retry timer is not set", resolution: "Set Error retry timer (Host Setup)." },
  { code: "F000D", brand: "Genmega", description: "RMS Password is not set when RMS is enabled", resolution: "Set RMS Password (Host Setup)." },
  { code: "F000E", brand: "Genmega", description: "RMS phone number is not set when RMS send is enabled", resolution: "Set RMS Phone number (Host Setup)." },
  { code: "F000F", brand: "Genmega", description: "Terminal ID is not set", resolution: "Set Terminal ID number (Host Setup)." },
  { code: "F0010", brand: "Genmega", description: "Routing ID is not set", resolution: "Set Routing ID number (Host Setup)." },
  { code: "F0011", brand: "Genmega", description: "Master Key Serial number is not set", resolution: "Set Master Key serial number (Host Setup)." },
  { code: "F0013", brand: "Genmega", description: "NVRAM Failure", resolution: "Fatal error, defective memory chip. Replace Mainboard." },
  { code: "F0014", brand: "Genmega", description: "NVRAM Failure", resolution: "Fatal error, defective memory chip. Replace Mainboard." },
  { code: "F0015", brand: "Genmega", description: "ATM Serial No. Empty", resolution: "None" },
  { code: "F0016", brand: "Genmega", description: "Default Master Password is not changed", resolution: "None" },
  { code: "F0020", brand: "Genmega", description: "Host IP Address is not inputted", resolution: "None" },
  { code: "F0021", brand: "Genmega", description: "RMS IP or Port is not inputted in RMS Enable", resolution: "None" },
  { code: "P0001", brand: "Genmega", description: "Deposit Error", resolution: "Deposit Error" },
  { code: "P0002", brand: "Genmega", description: "Deposit Timeout", resolution: "Deposit Timeout" },
  { code: "P0003", brand: "Genmega", description: "Invalid Deposit", resolution: "Invalid Deposit" },
  { code: "P0004", brand: "Genmega", description: "Deposit Cancelled", resolution: "Deposit Cancelled" },
  { code: "PDN01", brand: "Genmega", description: "EPP Communication Error", resolution: "None" },
  { code: "W0001", brand: "Genmega", description: "WebRMS failed to dial into the ATM", resolution: "This does not mean the ATM is down — WebRMS could not dial into the ATM after three attempts. Make sure the ATM is turned on, the phone line fits securely on both ends, and is not shared with a voice phone." },
  { code: "W0002", brand: "Genmega", description: "WebRMS low cash warning", resolution: "Courtesy alert that the total bill count is under a certain amount. Update your preferences through the website to change this warning." },
  { code: "W0003", brand: "Genmega", description: "WebRMS could not retrieve the local ATM time", resolution: "WebRMS retrieved the journal information but could not find the ATM's local time. Make sure you are running the latest application version." },
  { code: "W0004", brand: "Genmega", description: "ATM time is incorrect", resolution: "WebRMS detected that the ATM probably has incorrect date and time settings. Go to the ATM location and manually reset the correct date with the Master Password." },
  { code: "W0005", brand: "Genmega", description: "ATM was in Operator mode during dial-in", resolution: "Not an error — a warning that someone was on-site at the ATM and used its Operator Function menu." },
  { code: "W0006", brand: "Genmega", description: "WebRMS failed to dial into ATM for more than 3 consecutive days", resolution: "Check with the merchant and/or site owner to ensure the ATM is turned on at all times and not sharing the line with another device." },

  // ==================== HYOSUNG ====================
  { code: "0", brand: "Hyosung", description: "Normal Status", resolution: "Normal Status" },
  { code: "20001", brand: "Hyosung", description: "Unable to detect a cassette", resolution: "Remove and replace cassette. Check the micro-switch on the inside left wall of the dispenser. Adjust if needed. Check the white plastic clips that hold the cassette in place — if broken the cassette will not stay in the dispenser." },
  { code: "20002", brand: "Hyosung", description: "Low Cash", resolution: "Low cash warning sensor is open. When 'Low Cash Warning' is enabled, this sensor opens when the cassette reaches (~75 bills). If typically stocked with low bills, consider disabling this function." },
  { code: "20003", brand: "Hyosung", description: "Reject Bin is Full", resolution: "Empty reject bin. If bin is empty, do a Cassette Total from the settlement menu. If that doesn't help, check that AP, BIOS and CDU ROM versions are compatible." },
  { code: "20004", brand: "Hyosung", description: "Vault Door is Open", resolution: "Check vault door switch (white plunger switch in upper left corner of vault). Check that the black and white 2-wire connector is properly connected at rear of main board. Move the vault switch forward to aid door clearance. Check for continuity between the switch and mainboard connector." },
  { code: "20005", brand: "Hyosung", description: "CDU Type Mismatch", resolution: "CDU ROM does not match AP software. The dispenser and mainboard must share the same country code (USA or Canada). If they don't match, reprogram the CDU. Also check if wrong parameters were entered when the CDU was programmed." },
  { code: "20010", brand: "Hyosung", description: "Receipt Paper Jam", resolution: "Remove jammed paper. Release receipt paper drawer by pressing the tab with the green sticker at the front of the printer. You may have to remove the printer to locate difficult jams. Do NOT use metal objects — use a business card or stiff paper. Use only 21# paper." },
  { code: "20012", brand: "Hyosung", description: "Receipt printer feed lever open", resolution: "Close the feed tray on the printer. If already closed, try opening and closing it, try the printer reset switch. Otherwise the printer may require service." },
  { code: "20013", brand: "Hyosung", description: "Receipt paper is empty", resolution: "Replenish the paper roll. If paper is already in the printer, look for jams or obstructions. Try the printer reset switch. If error persists, the printer may require service." },
  { code: "20014", brand: "Hyosung", description: "Thermal printer is overheated", resolution: "Allow the printer to cool and try again. Try the reset button on the printer. If this error persists, the printer will require service." },
  { code: "20215", brand: "Hyosung", description: "CDU detects bills prior to dispensing (CS2 sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts — loose belts can slip off rollers and block sensors." },
  { code: "21315", brand: "Hyosung", description: "CDU detects bills prior to dispensing (CS13 sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "21A15", brand: "Hyosung", description: "CDU detects bills prior to dispensing (CS1A sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "21B15", brand: "Hyosung", description: "CDU detects bills prior to dispensing (CS1B sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "24A15", brand: "Hyosung", description: "CDU detects bills prior to dispensing (CS4A sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "24B15", brand: "Hyosung", description: "CDU detects bills prior to dispensing (CS4B sensor)", resolution: "Remove any jammed bills. If no bills present, use compressed air to clean the dispenser. Check and reseat all belts." },
  { code: "90001", brand: "Hyosung", description: "Error during card swipe", resolution: "Occurs when customer attempts to swipe card unsuccessfully. May indicate card reader needs cleaning, repositioning, or the customer didn't swipe properly. If persistent, clean and test the card reader in diagnostics. Very common — does not usually indicate a bad part." },
  { code: "A0008", brand: "Hyosung", description: "Receipt paper cutter error", resolution: "Remove any jammed paper. You may need to remove the printer to clear jams. Do not use metal objects — use a business card or stiff paper. Try the reset button or have the printer serviced." },
  { code: "A0803", brand: "Hyosung", description: "Receipt Paper Jam", resolution: "Remove jammed paper. Release receipt paper drawer by pressing the tab with the green sticker. You may need to remove the printer from the ATM to access the jam. Do NOT use metal objects." },
  { code: "A0808", brand: "Hyosung", description: "Receipt paper cutter error", resolution: "Remove any jammed paper. You may need to remove the printer to clear jams. Do not use metal objects — use a business card or stiff paper. Try the reset button or have the printer serviced." },
  { code: "ADN04", brand: "Hyosung", description: "Printer connection error", resolution: "Check cables between Printer and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Try the reset button on the printer. If consistent, the printer or mainboard may require service." },
  { code: "ADN0F", brand: "Hyosung", description: "Printer connection error", resolution: "Check cables between Printer and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Try the reset button. If consistent, printer or mainboard may require service." },
  { code: "ADNxx", brand: "Hyosung", description: "Printer connection error", resolution: "Check cables between Printer and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Try the reset button. If consistent, printer or mainboard may require service." },
  { code: "Axxx2", brand: "Hyosung", description: "Thermal printer overheated during operation", resolution: "Allow the printer to cool and try again. Try the reset button. If this error persists, the printer will require service." },
  { code: "Axxx3", brand: "Hyosung", description: "Receipt Paper Jam", resolution: "Remove jammed paper. Release receipt paper drawer by pressing the tab with the green sticker. You may need to remove the printer from the ATM to access the jam. Do NOT use metal objects." },
  { code: "Axxx4", brand: "Hyosung", description: "Receipt paper is empty", resolution: "Replenish the paper roll. If roll is ok, try the reset button. Otherwise the printer needs service." },
  { code: "Axxx5", brand: "Hyosung", description: "Receipt paper jamming during loading", resolution: "Remove any jammed paper and reload. You may need to remove the printer to clear jams. Do not use metal objects. Try the reset button or have the printer serviced." },
  { code: "C0011", brand: "Hyosung", description: "CDU sensor is tripped", resolution: "During dispense, the sensor at the front of the CDU shows a blockage (CS13 or CS2). Usually a bill bouncing back from the cash tray. Check the front of the CDU and cash tray for blockage. Reinitialize the ATM to put back in service." },
  { code: "C0014", brand: "Hyosung", description: "CDU sensor is tripped", resolution: "Similar to C0011 — indicates a bill jam close to the exit of the CDU or near the reject bin. Check for jammed notes or blocked sensors." },
  { code: "C001x", brand: "Hyosung", description: "CDU sensor is tripped", resolution: "Typically a C0011 error — bill jam at the exit sensor of the Cash Dispenser. Usually caused by a customer putting fingers in the cash drawer during dispense. You can loosen the screws that hold the dispenser and slide it back." },
  { code: "C0028", brand: "Hyosung", description: "CDU sensor is tripped", resolution: "Check dispenser for jammed bills and restart the machine. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C002x", brand: "Hyosung", description: "CDU sensor is tripped", resolution: "Check dispenser for jammed bills and restart the machine. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0030", brand: "Hyosung", description: "CDU motor failure", resolution: "Motor speed (measured at the encoder wheel) was not within spec. Verify that CS8 or encoder wheel sensor is in place and wire connection is good. Can indicate a bad motor or encoder sensor." },
  { code: "C0031", brand: "Hyosung", description: "CDU Gate solenoid error", resolution: "The CDU did not respond to its solenoid function check. Check the wiring connections to the solenoid(s) and to the CDU main board." },
  { code: "C0032", brand: "Hyosung", description: "Outlet solenoid error", resolution: "Check and verify all connections to the dispenser circuit board. Check wiring to the solenoid(s)." },
  { code: "C0033", brand: "Hyosung", description: "CDU Encoder error", resolution: "Usually caused by loss of battery power to the CDU mainboard. The only way to recover is to reprogram the CDU data. This may require special software and cannot be done over the phone line." },
  { code: "C0034", brand: "Hyosung", description: "Double Note detect module failure", resolution: "Double detect module reporting error. Check wiring to the module." },
  { code: "C0035", brand: "Hyosung", description: "Double Note detect module failure (2)", resolution: "Double detect module reporting error. Check wiring to the module." },
  { code: "C0036", brand: "Hyosung", description: "Detected notes in path before initializing", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0037", brand: "Hyosung", description: "Sensor for detecting Double covered during dispensing", resolution: "Check cable running to sensors and make sure they are securely placed. These sensors are next to the feed belts where the money is picked." },
  { code: "C0039", brand: "Hyosung", description: "Gate sensor open during initializing", resolution: "Check the sensor activated when you close the reject bin door (2k/4k dispensers only). Check the springs on the underside of the solenoids — one may be disconnected. Otherwise the CDU will require repair/replacement." },
  { code: "C003B", brand: "Hyosung", description: "Notes detected during installation", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0040", brand: "Hyosung", description: "Cassette removed during dispense", resolution: "Reset the cassette. Check position of microswitch on right rear wall of cassette bay in the dispenser. Check the condition of the white plastic cassette retaining clips." },
  { code: "C0041", brand: "Hyosung", description: "Tried to dispense notes more than 5 times", resolution: "Check the condition of the cash in the cassette. Verify cash is of good quality. The CDU belts or cassette rollers may need to be cleaned (rubbing alcohol). Check that the denomination in Transaction Setup matches the actual denomination loaded." },
  { code: "C0042", brand: "Hyosung", description: "Note jam", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0043", brand: "Hyosung", description: "More than 10 notes rejected during one transaction", resolution: "Verify the quality of the cash. Straighten and shuffle cash in the cassette. Check the reject analysis (reports menu). If cash is good quality, try cleaning the cassette and dispenser. Otherwise service may be required." },
  { code: "C0044", brand: "Hyosung", description: "More than 5 notes rejected consecutively", resolution: "Verify the quality of the cash. Straighten and shuffle cash in the cassette. Check the reject analysis (reports menu). If cash is good quality, try cleaning. Otherwise service may be required." },
  { code: "C0045", brand: "Hyosung", description: "Notes Overdispensed", resolution: "Check NS4 Sensor." },
  { code: "C0046", brand: "Hyosung", description: "CDU Hardware Failure", resolution: "Error reported during CDU initialization. Check cabling and potential blockages and power cycle ATM. CDU Board may have dropped firmware." },
  { code: "C0047", brand: "Hyosung", description: "Feed error", resolution: "Dispenser attempts to pull a bill from the cassette and is unsuccessful before timing out. Can be as simple as the cassette being empty, rollers needing cleaning, or a firmware upgrade to the CDU may be needed." },
  { code: "C0048", brand: "Hyosung", description: "Incorrect bill count", resolution: "Verify cash count in the Settlement menu." },
  { code: "C004A", brand: "Hyosung", description: "Jammed notes", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C004B", brand: "Hyosung", description: "Long note detected 3 times consecutively", resolution: "Verify the quality of the cash. Straighten and shuffle cash in the cassette. Try cleaning the cassette and dispenser. If persistent, service may be required." },
  { code: "C004C", brand: "Hyosung", description: "Miscount of notes between sensors", resolution: "Verify operation of exit gate. Check the number of dispensed notes. Clean the dispenser and test using diagnostics. Dispenser may require service." },
  { code: "C004D", brand: "Hyosung", description: "Cash cassette not properly set", resolution: "Reset the cassette. Check position of microswitch on right rear wall of cassette bay. Check condition of white plastic cassette retaining clips. MB1000: check condition of the clutch alignment screw." },
  { code: "C004E", brand: "Hyosung", description: "Miscount of notes between sensors", resolution: "Test CDU using diagnostics. Use journal to verify amount of dispensed notes versus requested notes. Clean dispenser and cassette. If error persists, dispenser may require service." },
  { code: "C004F", brand: "Hyosung", description: "Miscount of notes between sensors", resolution: "Test CDU using diagnostics. Use journal to verify dispensed notes vs requested. Clean dispenser and cassette. If error persists, dispenser may require service." },
  { code: "C0050", brand: "Hyosung", description: "Power failure during dispense", resolution: "Remove any notes from path. Before reinitializing, verify amount of dispensed notes in the cassette against the journal." },
  { code: "C0051", brand: "Hyosung", description: "Over 150 notes requested", resolution: "Possibly due to too many rejects. Check the Reject Analysis. Cash quality and condition of rollers in the cassette can affect this condition." },
  { code: "C0052", brand: "Hyosung", description: "Detected notes in path after dispense", resolution: "Remove any notes from path. Verify amount of dispensed notes. Clean dispenser. Verify bill count against the journal." },
  { code: "C0053", brand: "Hyosung", description: "CDU double detect module failure", resolution: "Double detect module may require adjustment. Check wiring and CDU mainboard connections." },
  { code: "C0055", brand: "Hyosung", description: "Detected long notes at outlet sensor", resolution: "Typically a bounce back of a bill during dispense causing the exit sensor to remain blocked longer than expected. See C0011." },
  { code: "C0056", brand: "Hyosung", description: "Exit gate sensor failure", resolution: "Check condition of exit gate and the exit gate sensor." },
  { code: "C0057", brand: "Hyosung", description: "Cassette information is not properly set", resolution: "CDU programming is not accurate or complete." },
  { code: "C0059", brand: "Hyosung", description: "Cash cassette 2 removed prior to dispense", resolution: "Set the cash cassette. Inspect the cassette detection microswitch. Reposition if necessary." },
  { code: "C005A", brand: "Hyosung", description: "Cash cassette 1 removed prior to dispense", resolution: "Set the cash cassette. Inspect the cassette detection microswitch. Reposition if necessary." },
  { code: "C005B", brand: "Hyosung", description: "Cash cassette 2 misfeed", resolution: "Check cassette for jams. Check condition of bills in cassette." },
  { code: "C005D", brand: "Hyosung", description: "Double detect constantly", resolution: "Inspect double detect module and adjust as necessary. Check and clean the cassette and rollers. Verify quality of cash." },
  { code: "C005E", brand: "Hyosung", description: "Dispense command size check error", resolution: "Re-initialize machine, verify connections to mainboard. Check for unplugged sensors." },
  { code: "C005F", brand: "Hyosung", description: "Dispense command error", resolution: "Re-initialize machine, verify connections, check for unplugged sensors." },
  { code: "C006x", brand: "Hyosung", description: "Sensor failure", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C007x", brand: "Hyosung", description: "Sensor failure", resolution: "Check for notes in the Cash Dispenser. If no bills present, use compressed air to clean the dispenser. Otherwise the dispenser may require service." },
  { code: "C0082", brand: "Hyosung", description: "Shutter failure", resolution: "Check all wiring connections to CDU mainboard. Reinitialize CDU." },
  { code: "C0083", brand: "Hyosung", description: "Stacker sensor failure", resolution: "Check all wiring connections to CDU mainboard. Reinitialize CDU." },
  { code: "C0084", brand: "Hyosung", description: "Shutter close error", resolution: "Check all wiring connections to CDU mainboard. Reinitialize CDU." },
  { code: "C009F", brand: "Hyosung", description: "Cassette misfeed error", resolution: "Check if notes are available in cassette." },
  { code: "C00AB", brand: "Hyosung", description: "Notes detected before initializing", resolution: "Clear notes from dispenser. Possibly dust or foreign object blocking sensor." },
  { code: "C00C1", brand: "Hyosung", description: "Cassette 1 bill jam during dispense operation", resolution: "Remove bill jam." },
  { code: "C00C7", brand: "Hyosung", description: "CS12 Sensor blocked", resolution: "MB2100T: The CS12 sensor at the upper part of the cash tray was blocked while dispensing or initializing. Clear the cash tray of any bills or foreign objects. If error persists, the vault assembly may need to be removed to inspect the sensors." },
  { code: "C00C8", brand: "Hyosung", description: "CS14 Sensor blocked", resolution: "MB2100T: The CS14 sensor close to the front of the cash tray was blocked. Clear the cash tray of any bills or foreign objects. If error persists, the vault assembly may need to be removed." },
  { code: "C00C9", brand: "Hyosung", description: "CS12 & CS14 Sensors blocked", resolution: "MB2100T: Both CS12 and CS14 sensors were blocked. These sensors prevent tampering with the bill path. Clear the cash tray of any bills or foreign objects. If error persists, the vault assembly may need to be removed." },
  { code: "C00D0", brand: "Hyosung", description: "Sensor block while dispensing", resolution: "MB2100T: A blockage was detected between the CS13 (CDU exit gate) and CS12 cash tray sensors. There may be a note stuck in the upper part of the cash tray ramp. Clear the cash tray of notes or foreign objects. Open the vault and slide the dispenser back to access the exit gate area." },
  { code: "C00D1", brand: "Hyosung", description: "Sensor blocked while dispensing", resolution: "MB2100T: A blockage was detected between the CS12 (upper cash tray sensor) and CS14 (lower cash tray sensor). There may be a note stuck in the cash tray ramp. Clear the cash tray of notes or foreign objects." },
  { code: "C00E0", brand: "Hyosung", description: "NS2A, NS2B dark", resolution: "Nanocash only — verify connections to sensors. Check wiring to mainboard." },
  { code: "C00E1", brand: "Hyosung", description: "NS4 dark", resolution: "Verify connections to NS4 sensor. Check all wiring to mainboard." },
  { code: "C00FF", brand: "Hyosung", description: "Sensor blocked", resolution: "N/A" },
  { code: "CANCE", brand: "Hyosung", description: "User canceled transaction at surcharge", resolution: "Not an error — a statistic showing how many users respond 'no' to the surcharge notification." },
  { code: "CDN01", brand: "Hyosung", description: "No Response after send command", resolution: "None" },
  { code: "CDN05", brand: "Hyosung", description: "CDU connection failure", resolution: "Check cables between CDU and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Only a concern if repeated. Outside interference may cause it (neon signs, lights)." },
  { code: "CDN0F", brand: "Hyosung", description: "CDU connection failure", resolution: "Check cables between CDU and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Only a concern if repeated." },
  { code: "CDN11", brand: "Hyosung", description: "No Response after 3 retry of command", resolution: "None" },
  { code: "CDN12", brand: "Hyosung", description: "No Response between ENQ-ACK after 5 retry of ENQ", resolution: "None" },
  { code: "CDN13", brand: "Hyosung", description: "No Response after 5 retry due to timeout", resolution: "None" },
  { code: "CDNxx", brand: "Hyosung", description: "CDU connection failure", resolution: "Check cables between CDU and Mainboard, remove and re-connect. Use electrical parts contact cleaner on terminals. Only a concern if repeated." },
  { code: "D0001", brand: "Hyosung", description: "Modem initialization error", resolution: "Check modem in diagnostics or modem test. If persistent, could be a defective modem. Check Modem Initial String. One or two instances does not usually indicate a defective part." },
  { code: "D0002", brand: "Hyosung", description: "Reversal transaction failed", resolution: "The ATM attempted to do a reversal and could not. Check transaction with the processor. Verify CDU functionality with diagnostics. Verify phone connection. Look in error summary for D1800, D2000." },
  { code: "D0005", brand: "Hyosung", description: "Undefined network processing error", resolution: "Code reported by host processor. Contact your ISO or processor if you encounter an excessive amount of these errors or cannot complete a test transaction." },
  { code: "D0011", brand: "Hyosung", description: "Format error in the message", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0012", brand: "Hyosung", description: "Invalid Transaction", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0013", brand: "Hyosung", description: "Invalid Amount", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0014", brand: "Hyosung", description: "Invalid Card Number", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0019", brand: "Hyosung", description: "Reenter the entire transaction", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0020", brand: "Hyosung", description: "Surcharge screen should have been displayed", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0024", brand: "Hyosung", description: "Exceeds issuer withdrawal limit", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0031", brand: "Hyosung", description: "Issuer financial institution not supported by processor", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0039", brand: "Hyosung", description: "No credit account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0041", brand: "Hyosung", description: "No credit account found for the CCN", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0043", brand: "Hyosung", description: "Stolen Card", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0050", brand: "Hyosung", description: "Transaction is not approved", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0051", brand: "Hyosung", description: "Insufficient funds", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0052", brand: "Hyosung", description: "No checking account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0053", brand: "Hyosung", description: "No savings account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0054", brand: "Hyosung", description: "Expired Card", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0055", brand: "Hyosung", description: "Invalid PIN", resolution: "Code reported from host processor. Verify all programming. For new installations, if master keys are not bound properly or Terminal ID is not active, this can occur. If programming appears correct, contact the processor and have them trace the Terminal ID." },
  { code: "D0056", brand: "Hyosung", description: "No card record found", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0057", brand: "Hyosung", description: "Transaction not permitted – card", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0058", brand: "Hyosung", description: "Transaction not permitted – Terminal", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0059", brand: "Hyosung", description: "Customer should contact financial institution", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0060", brand: "Hyosung", description: "Allowable withdrawal limit exceeded", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0061", brand: "Hyosung", description: "Exceeded withdrawal limit", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0065", brand: "Hyosung", description: "Exceeds withdrawal frequency limit", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0067", brand: "Hyosung", description: "Capture card at the terminal", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0075", brand: "Hyosung", description: "Number of PIN tries exceeded", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0078", brand: "Hyosung", description: "No Account", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0080", brand: "Hyosung", description: "Invalid Date", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0081", brand: "Hyosung", description: "Timeout: response not received in time allowed", resolution: "Code reported by host processor (Shazam). Contact your ISO or processor." },
  { code: "D0082", brand: "Hyosung", description: "Cashback limit exceeded", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0083", brand: "Hyosung", description: "Cannot verify PIN", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0084", brand: "Hyosung", description: "Processor not available", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0086", brand: "Hyosung", description: "Cannot verify PIN", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0090", brand: "Hyosung", description: "Cutoff complete for terminal", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0091", brand: "Hyosung", description: "Bank unavailable", resolution: "Code reported by host processor. Contact your ISO or processor." },
  { code: "D0092", brand: "Hyosung", description: "System unavailable", resolution: "Code reported by host processor. Possible Incorrect Check Digit (Master Keys). Contact your ISO or processor." },
  { code: "D0093", brand: "Hyosung", description: "Transaction serial number mismatch", resolution: "Verify all programming, contact host processor." },
  { code: "D0094", brand: "Hyosung", description: "Record format mismatch", resolution: "Verify all programming, contact host processor." },
  { code: "D0095", brand: "Hyosung", description: "Routing ID mismatch", resolution: "Verify Routing ID number, contact host processor." },
  { code: "D0096", brand: "Hyosung", description: "Terminal ID mismatch", resolution: "Verify Terminal ID number, contact host processor." },
  { code: "D0097", brand: "Hyosung", description: "Response type mismatch (reversal)", resolution: "Verify all programming, contact host processor." },
  { code: "D0098", brand: "Hyosung", description: "Response type mismatch (day-close)", resolution: "Verify all programming, contact host processor." },
  { code: "D0099", brand: "Hyosung", description: "Response type mismatch (Configuration)", resolution: "Verify all programming, contact host processor." },
  { code: "D009A", brand: "Hyosung", description: "Response type mismatch (Withdrawal, Balance, Transfer)", resolution: "Verify all programming, contact host processor." },
  { code: "D009B", brand: "Hyosung", description: "STX omitted", resolution: "Verify all programming, contact host processor." },
  { code: "D009C", brand: "Hyosung", description: "ETX omitted", resolution: "Verify all programming, contact host processor." },
  { code: "D009D", brand: "Hyosung", description: "FS omitted (after response code)", resolution: "Verify Mini-Bank Software version matches host processor. Contact host processor." },
  { code: "D009E", brand: "Hyosung", description: "FS omitted (after retrieval reference number)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D009F", brand: "Hyosung", description: "FS omitted (after system trace audit number)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A0", brand: "Hyosung", description: "FS omitted (after account balance)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A1", brand: "Hyosung", description: "FS omitted (after available balance)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A2", brand: "Hyosung", description: "FS omitted (after available balance)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor. Check T-DES Type." },
  { code: "D00A3", brand: "Hyosung", description: "FS omitted (after authorization response text)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A4", brand: "Hyosung", description: "ETX is in wrong place", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A5", brand: "Hyosung", description: "FS omitted (after total cash dispense amount in day close)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A6", brand: "Hyosung", description: "FS omitted (after total non cash dispense amount in day close)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A7", brand: "Hyosung", description: "FS omitted (after surcharge amount in day close message)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00A8", brand: "Hyosung", description: "FS omitted (after surcharge amount in configuration message)", resolution: "Verify all programming. Check that Dual Master Key is disabled (non Coredata). Contact host processor." },
  { code: "D00A9", brand: "Hyosung", description: "ETX omitted (from configuration message)", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D00B0", brand: "Hyosung", description: "Invalid Terminal ID", resolution: "Contact host processor." },
  { code: "D0100", brand: "Hyosung", description: "Transaction approved", resolution: "None" },
  { code: "D0101", brand: "Hyosung", description: "Expired card", resolution: "None" },
  { code: "D0102", brand: "Hyosung", description: "Unauthorized usage", resolution: "None" },
  { code: "D0103", brand: "Hyosung", description: "PIN error", resolution: "None" },
  { code: "D0104", brand: "Hyosung", description: "Invalid PIN", resolution: "None" },
  { code: "D0105", brand: "Hyosung", description: "Bank unavailable", resolution: "None" },
  { code: "D0106", brand: "Hyosung", description: "Card not supported", resolution: "None" },
  { code: "D0107", brand: "Hyosung", description: "Insufficient funds", resolution: "None" },
  { code: "D0108", brand: "Hyosung", description: "Ineligible transaction", resolution: "None" },
  { code: "D0109", brand: "Hyosung", description: "Ineligible account", resolution: "None" },
  { code: "D0110", brand: "Hyosung", description: "Number of daily withdrawals exceeded", resolution: "None" },
  { code: "D0111", brand: "Hyosung", description: "Cannot process transaction", resolution: "None" },
  { code: "D0112", brand: "Hyosung", description: "Amount too large", resolution: "None" },
  { code: "D0113", brand: "Hyosung", description: "Account closed", resolution: "None" },
  { code: "D0114", brand: "Hyosung", description: "PIN tries exceeded", resolution: "None" },
  { code: "D0115", brand: "Hyosung", description: "Database problem", resolution: "None" },
  { code: "D0116", brand: "Hyosung", description: "Withdrawal limit already reached", resolution: "None" },
  { code: "D0117", brand: "Hyosung", description: "Invalid amount", resolution: "None" },
  { code: "D0118", brand: "Hyosung", description: "External decline", resolution: "None" },
  { code: "D0119", brand: "Hyosung", description: "System error", resolution: "None" },
  { code: "D0120", brand: "Hyosung", description: "Contact card issuer", resolution: "None" },
  { code: "D0121", brand: "Hyosung", description: "Routing lookup problem", resolution: "None" },
  { code: "D0122", brand: "Hyosung", description: "Message edit error", resolution: "None" },
  { code: "D0123", brand: "Hyosung", description: "Transaction not supported", resolution: "None" },
  { code: "D0124", brand: "Hyosung", description: "Insufficient funds", resolution: "None" },
  { code: "D0125", brand: "Hyosung", description: "Western Union sender data error", resolution: "None" },
  { code: "D0126", brand: "Hyosung", description: "Western Union receiver data error", resolution: "None" },
  { code: "D0127", brand: "Hyosung", description: "CRC error", resolution: "None" },
  { code: "D0128", brand: "Hyosung", description: "Pre-pay transaction failed", resolution: "None" },
  { code: "D0129", brand: "Hyosung", description: "Pre-pay transaction rejected", resolution: "None" },
  { code: "D0130", brand: "Hyosung", description: "Invalid mobile phone number", resolution: "None" },
  { code: "D0131", brand: "Hyosung", description: "Pre-pay account limit reached", resolution: "None" },
  { code: "D0132", brand: "Hyosung", description: "Pre-pay system unavailable", resolution: "None" },
  { code: "D0133", brand: "Hyosung", description: "Response would exceed message size limit", resolution: "None" },
  { code: "D0134", brand: "Hyosung", description: "Necessary information missing to process transaction", resolution: "None" },
  { code: "D0135", brand: "Hyosung", description: "Second Invalid PIN (one try left before deactivation)", resolution: "None" },
  { code: "D0300", brand: "Hyosung", description: "Modem is not responding", resolution: "Use diagnostic or modem test to test modem. If error is persistent, modem may be defective." },
  { code: "D1000", brand: "Hyosung", description: "No Connection", resolution: "Use diagnostic or modem test to test modem. If error is persistent, modem may be defective." },
  { code: "D1100", brand: "Hyosung", description: "ENQ not received from host", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D1200", brand: "Hyosung", description: "Transmission error", resolution: "Use diagnostic or modem test to test modem. If error is persistent, modem may be defective." },
  { code: "D1300", brand: "Hyosung", description: "NAK sent 3 times to host", resolution: "Verify host phone number. If persistent, it could be a defective modem." },
  { code: "D1500", brand: "Hyosung", description: "Modem connection timeout – host not responding", resolution: "Verify host phone number and modem speed. If consistent, it can be a defective modem." },
  { code: "D1701", brand: "Hyosung", description: "Stutter tone on phone line", resolution: "Check for stutter tone on phone line (voicemail)." },
  { code: "D1702", brand: "Hyosung", description: "Modem connection error", resolution: "Phone line will not support data communication. In-line filter may help. Check for excessive EMI from outside sources (neon sign, freezer). Check all programming (especially Dual Master Key setting and Host Processor Mode)." },
  { code: "D1704", brand: "Hyosung", description: "Modem connection error", resolution: "Phone line will not support data communication. In-line filter may help. Check for excessive EMI from outside sources. Check all programming (especially Dual Master Key setting and Host Processor Mode)." },
  { code: "D1706", brand: "Hyosung", description: "Modem connection error", resolution: "Phone line will not support data communication. In-line filter may help. Check for excessive EMI from outside sources. Check all programming." },
  { code: "D170x", brand: "Hyosung", description: "Modem cannot support connection – excessive line noise", resolution: "Phone line will not support data communication. In-line filter may fix this. Check for excessive EMI from outside sources. Check all programming (especially Dual Master Key setting and Host Processor Mode)." },
  { code: "D1800", brand: "Hyosung", description: "No dial tone", resolution: "Verify that incoming phone line is plugged into 'Line' rather than 'Phone' on mainboard. Phone line may be in use or shared with another device (FAX, POS, phone). This error occurs only if there is no dial tone at the mainboard." },
  { code: "D1900", brand: "Hyosung", description: "No answer", resolution: "Verify host phone number. There is no answer from the host modem." },
  { code: "D2000", brand: "Hyosung", description: "Phone line Busy", resolution: "Verify host phone number — call line with handset and check for busy signal. ATM modem is receiving a busy signal when it dials out." },
  { code: "D2100", brand: "Hyosung", description: "Modem initialization error", resolution: "Check modem in diagnostics or modem test. If persistent, could be a defective modem. One or two instances does not usually indicate a defective part." },
  { code: "D2200", brand: "Hyosung", description: "EOT not received from host", resolution: "Verify all programming and Mini-Bank Software version. Contact host processor." },
  { code: "D2500", brand: "Hyosung", description: "Cannot connect to the host", resolution: "Check the connection." },
  { code: "D2510", brand: "Hyosung", description: "Timeout while Sending", resolution: "None" },
  { code: "D2511", brand: "Hyosung", description: "Communication error while Sending", resolution: "None" },
  { code: "D2513", brand: "Hyosung", description: "Timeout while Receiving", resolution: "None" },
  { code: "D2514", brand: "Hyosung", description: "Communication error while Receiving", resolution: "None" },
  { code: "D2515", brand: "Hyosung", description: "Socket Error while Receiving", resolution: "None" },
  { code: "D3203", brand: "Hyosung", description: "Modem Initialization Error", resolution: "Reseat socket modem, then replace modem." },
  { code: "D3204", brand: "Hyosung", description: "Invalid Host phone number", resolution: "Verify the Host phone number is programmed correctly. Do not use spaces or dashes in the phone number string." },
  { code: "E000x", brand: "Hyosung", description: "RMS port failure / response timeout / modem failure / no dial tone", resolution: "Verify RMS settings (Host Setup)." },
  { code: "F0001", brand: "Hyosung", description: "Current Number of Bills is 0", resolution: "Load notes into the cash cassette — use Add Cassette function in Settlement." },
  { code: "F0002", brand: "Hyosung", description: "No Surcharge Owner set", resolution: "Set Surcharge owner (Customer Setup)." },
  { code: "F0003", brand: "Hyosung", description: "No Surcharge Amount", resolution: "Set Surcharge amount (Customer Setup)." },
  { code: "F0004", brand: "Hyosung", description: "No refresh timer set when advertisement is enabled", resolution: "Set refresh timer (Customer Setup)." },
  { code: "F0005", brand: "Hyosung", description: "No Advertisement text when advertisement is enabled", resolution: "Set Advertisement text (Customer Setup)." },
  { code: "F0006", brand: "Hyosung", description: "Dispense limit set error (must be less than 25 notes)", resolution: "Set Dispense limit (Transaction Setup)." },
  { code: "F0007", brand: "Hyosung", description: "Denomination Set error", resolution: "Valid Denominations are $10, $20, $50, $100 (Transaction Setup)." },
  { code: "F0008", brand: "Hyosung", description: "Fast Cash Set error (cannot exceed dispense limit)", resolution: "Check fast cash settings (Transaction Setup)." },
  { code: "F0009", brand: "Hyosung", description: "Master Key index is invalid", resolution: "Check Master Key index — verify checksum (Host Setup)." },
  { code: "F000A", brand: "Hyosung", description: "Master Key is empty", resolution: "Check Master Key checksum — reinject key (Host Setup)." },
  { code: "F000B", brand: "Hyosung", description: "Host Telephone Number is not set", resolution: "Set Host Telephone Number (Host Setup)." },
  { code: "F000C", brand: "Hyosung", description: "Error Retry timer is not set", resolution: "Set Error retry timer (Host Setup)." },
  { code: "F000D", brand: "Hyosung", description: "RMS Password is not set when RMS is enabled", resolution: "Set RMS Password (Host Setup)." },
  { code: "F000E", brand: "Hyosung", description: "RMS phone number is not set when RMS send is enabled", resolution: "Set RMS Phone number (Host Setup)." },
  { code: "F000F", brand: "Hyosung", description: "Terminal ID is not set", resolution: "Set Terminal ID number (Host Setup)." },
  { code: "F0010", brand: "Hyosung", description: "Routing ID is not set", resolution: "Set Routing ID number (Host Setup)." },
  { code: "F0011", brand: "Hyosung", description: "Master Key Serial number is not set", resolution: "Set Master Key serial number (Host Setup)." },
  { code: "F0013", brand: "Hyosung", description: "NVRAM Failure", resolution: "Fatal error, defective memory chip. Replace Mainboard." },
  { code: "F0014", brand: "Hyosung", description: "NVRAM Failure", resolution: "Fatal error, defective memory chip. Replace Mainboard." },
  { code: "F0015", brand: "Hyosung", description: "ATM Serial No. Empty", resolution: "None" },
  { code: "F0016", brand: "Hyosung", description: "Default Master Password is not changed", resolution: "None" },
  { code: "F0020", brand: "Hyosung", description: "Host IP Address is not inputted", resolution: "None" },
  { code: "F0021", brand: "Hyosung", description: "RMS IP or Port is not inputted in RMS Enable", resolution: "None" },
  { code: "P0001", brand: "Hyosung", description: "Deposit Error", resolution: "Deposit Error" },
  { code: "P0002", brand: "Hyosung", description: "Deposit Timeout", resolution: "Deposit Timeout" },
  { code: "P0003", brand: "Hyosung", description: "Invalid Deposit", resolution: "Invalid Deposit" },
  { code: "P0004", brand: "Hyosung", description: "Deposit Cancelled", resolution: "Deposit Cancelled" },
  { code: "PDN01", brand: "Hyosung", description: "EPP Communication Error", resolution: "None" },
  { code: "W0001", brand: "Hyosung", description: "WebRMS failed to dial into the ATM", resolution: "This does not mean the ATM is down — WebRMS could not dial into the ATM after three attempts. Make sure the ATM is turned on, the phone line fits securely on both ends, and is not shared with a voice phone." },
  { code: "W0002", brand: "Hyosung", description: "WebRMS low cash warning", resolution: "Courtesy alert that the total bill count is under a certain amount. Update your preferences through the website to change this warning." },
  { code: "W0003", brand: "Hyosung", description: "WebRMS could not retrieve the local ATM time", resolution: "WebRMS retrieved the journal information but could not find the ATM's local time. Make sure you are running the latest application version." },
  { code: "W0004", brand: "Hyosung", description: "ATM time is incorrect", resolution: "WebRMS detected that the ATM probably has incorrect date and time settings. Go to the ATM location and manually reset the correct date with the Master Password." },
  { code: "W0005", brand: "Hyosung", description: "ATM was in Operator mode during dial-in", resolution: "Not an error — a warning that someone was on-site at the ATM and used its Operator Function menu." },
  { code: "W0006", brand: "Hyosung", description: "WebRMS failed to dial into ATM for more than 3 consecutive days", resolution: "Check with the merchant and/or site owner to ensure the ATM is turned on at all times and not sharing the line with another device." },
];

export default errorCodes;

export const errorCodeManufacturers = ["All", "Genmega", "Hyosung"];
