// app/lib/products.js - Complete product database for OSO ATM Parts

export const products = [
  {
    "id": 1,
    "sku": "OSO-00001",
    "name": "Genmega ACU 7 Mainboard",
    "manufacturer": "Genmega",
    "category": "Mainboards",
    "cost": 600.00,
    "price": 700.00,
    "description": "CE, Main Board, ACU 7, Without Modem",
    "partNumber": "161110881",
    "image": "/products/acu7-mainboard.png",
    "inStock": true
  },
  {
    "id": 2,
    "sku": "OSO-00002",
    "name": "Genmega RCDU, Rear Load Dispenser, Without Cassette",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1037.00,
    "price": 1300.00,
    "description": "1-High, 2K RCDU, Rear Load Dispenser, Without Cassette",
    "partNumber": "151107931",
    "image": "/products/rcdu-rear-load-dispenser.png",
    "inStock": true
  },
  {
    "id": 3,
    "sku": "OSO-00003",
    "name": "Genmega NFC Card Reader",
    "manufacturer": "Genmega",
    "category": "Card Readers",
    "cost": 180.00,
    "price": 300.00,
    "description": "Genmega NFC/TAP VIVOPAY Card Reader NOTICE: Comes With Wire Harness & Install Template",
    "partNumber": "180102381",
    "image": "/products/nfc-card-reader.png",
    "inStock": true
  },
  {
    "id": 4,
    "sku": "OSO-00004",
    "name": "Genmega 2K Note Cassette, 1st",
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "1st Cassette, MCDU/HCDU/HPCDU/PCDU/RCDU",
    "partNumber": "141139501",
    "image": "/products/hcdu-2k-cassette.png",
    "inStock": true
  },
  {
    "id": 5,
    "sku": "OSO-00005",
    "name": "Genmega Mini High Bright Topper",
    "manufacturer": "Genmega",
    "category": "Toppers",
    "cost": 119.00,
    "price": 160.00,
    "description": "Mini HB Topper II",
    "partNumber": "110189141",
    "image": "/products/mini-high-bright-topper.png",
    "inStock": true
  },
  {
    "id": 6,
    "sku": "OSO-00006",
    "name": "S&G Electronic Lock",
    "manufacturer": "Hyosung & Genmega",
    "category": "Locks",
    "cost": 92.00,
    "price": 110.00,
    "description": "Electronic Lock With Keypad",
    "partNumber": "231114341",
    "image": "/products/sg-electronic-lock.png",
    "inStock": true
  },
  {
    "id": 7,
    "sku": "OSO-00007",
    "name": "Genmega SCDU / WCDU 1K Cassette",
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 334.00,
    "price": 400.00,
    "description": "1K Cassette NOTICE: Will Not Work With SCDU-E 2 High",
    "partNumber": "141170001",
    "image": "/products/scdu-wcdu-1k-cassette.png",
    "inStock": true
  },
  {
    "id": 8,
    "sku": "OSO-00008",
    "name": "Genmega SCDU Dispenser, Without Cassette",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 741.00,
    "price": 850.00,
    "description": "1K Dispenser Without Cassette",
    "partNumber": "151119851",
    "image": "/products/scdu-1k-dispenser.png",
    "inStock": true
  },
  {
    "id": 9,
    "sku": "OSO-00009",
    "name": "Genmega 2\" Printer Assembly",
    "manufacturer": "Genmega",
    "category": "Printers",
    "cost": 491.00,
    "price": 600.00,
    "description": "2\" Printer Assembly Without Image Print",
    "partNumber": "271110101",
    "image": "/products/printer-2inch-assembly.png",
    "inStock": true
  },
  {
    "id": 10,
    "sku": "OSO-00010",
    "name": "Genmega 2 High HCDU, Without Cassettes",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1116.00,
    "price": 1300.00,
    "description": "2 High, 4K HCDU Without Cassettes",
    "partNumber": "151110451",
    "image": "/products/hcdu-2high.png",
    "inStock": true
  },
  {
    "id": 11,
    "sku": "OSO-00011",
    "name": "Genmega / Hantle Power Supply",
    "manufacturer": "Genmega",
    "category": "Power Supplies",
    "cost": 294.00,
    "price": 350.00,
    "description": "Genmega Power Supply",
    "partNumber": "251118791",
    "image": "/products/power-supply.png",
    "inStock": true
  },
  {
    "id": 12,
    "sku": "OSO-00012",
    "name": "Hyosung Bezel Key",
    "manufacturer": "Hyosung",
    "category": "Keys & Accessories",
    "cost": 9.59,
    "price": 8.99,
    "description": "Fits All ATM Hyosung Model Types",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 13,
    "sku": "OSO-00013",
    "name": "ATM Wireless Antenna",
    "manufacturer": "Universal",
    "category": "Wireless/Connectivity",
    "cost": 12.99,
    "price": 11.99,
    "description": "Standard Antenna - Increases cellular reception, weatherized with magnetic base and 10 foot cord",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 14,
    "sku": "OSO-00014",
    "name": "Hyosung Printer Assembly",
    "manufacturer": "Hyosung",
    "category": "Printers",
    "cost": 719.99,
    "price": 683.99,
    "description": "Hyosung Receipt Printer Assembly",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 15,
    "sku": "OSO-00015",
    "name": "Hyosung Power Supply",
    "manufacturer": "Hyosung",
    "category": "Power Supplies",
    "cost": 347.99,
    "price": 330.99,
    "description": "New Revision Power Supply",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 16,
    "sku": "OSO-00016",
    "name": "Hyosung EMV Card Reader",
    "manufacturer": "Hyosung",
    "category": "Card Readers",
    "cost": 289.99,
    "price": 274.99,
    "description": "Hyosung ATM EMV chip replacement card reader - Card Reader Only. Not an upgrade kit",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 17,
    "sku": "OSO-00017",
    "name": "Hyosung LCD Display Panel with LED Backlight",
    "manufacturer": "Hyosung",
    "category": "LCD Displays",
    "cost": 275.99,
    "price": 261.99,
    "description": "New Revision LCD Display Panel w/o Electronics Size - 10.1\"",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 18,
    "sku": "OSO-00018",
    "name": "Hyosung NFC Reader Complete Kit for Halo II",
    "manufacturer": "Hyosung",
    "category": "Card Readers",
    "cost": 379.99,
    "price": 360.99,
    "description": "NFC Reader Complete Kit to include bracket and cables for Halo II",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 21,
    "sku": "OSO-00021",
    "name": "InHand IR302 4G Wireless Router",
    "manufacturer": "InHand",
    "category": "Wireless/Connectivity",
    "cost": 100.00,
    "price": 130.00,
    "description": "InHand IR302 4G LTE industrial router for ATM connectivity. Purchase outright.",
    "image": "/products/Inhand.png",
    "inStock": true
  },
  {
    "id": 26,
    "sku": "OSO-00026",
    "name": "Origin Wireless Router",
    "manufacturer": "Origin",
    "category": "Wireless/Connectivity",
    "cost": 86.99,
    "price": 82.99,
    "description": "Origin by Allpoint Wireless router for ATM connectivity.",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 27,
    "sku": "OSO-00027",
    "name": "Genmega Bezel Key, Type C415A, Two Keys",
    "manufacturer": "Genmega",
    "category": "Locks",
    "cost": 7.00,
    "price": 9.00,
    "description": "Genmega Bezel Key, Not For Nova or Kiosk",
    "partNumber": "230210581",
    "image": "/products/c415a-key.png",
    "inStock": true
  },
  {
    "id": 28,
    "sku": "OSO-00028",
    "name": "Genmega Barrel Key, Eagle, 1 Key",
    "manufacturer": "Genmega",
    "category": "Locks",
    "cost": 6.00,
    "price": 9.00,
    "description": "Genmega Barrel Key, Eagle, 1 Key",
    "partNumber": "230200591",
    "image": "/products/eagle-barrel-key.png",
    "inStock": true
  },
  {
    "id": 29,
    "sku": "OSO-00029",
    "name": "Genmega Keypad, PCI V5.X Certified, EPP B5",
    "manufacturer": "Genmega",
    "category": "Keypads",
    "cost": 437.00,
    "price": 550.00,
    "description": "EPP, PCI V5.X CERTIFIED, EPP B5. NOTICE: This Keypad Requires ATM Software Version V05.00.37 Or Higher",
    "partNumber": "201207541",
    "image": "/products/201207541.png",
    "inStock": true
  },
  {
    "id": 30,
    "sku": "OSO-00030",
    "name": "Gengmega EMV Card Reader, Type TDR",
    "manufacturer": "Genmega",
    "category": "Card Readers",
    "cost": 218.00,
    "price": 250.00,
    "description": "EMV Card Reader, Type TDR-R240N. NOTICE: This Is The Card Reader Only - No Cable Or Bracket Included",
    "partNumber": "241180071",
    "image": "/products/241180071.jpg",
    "inStock": true
  },
  {
    "id": 31,
    "sku": "OSO-00031",
    "name": "Genmega GT3000 LCD Upgrade Kit, Sunviewable 7\" LCD",
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 710.00,
    "price": 850.00,
    "description": "Upgrade Kit, Sunviewable 7\" LCD, GT3000 NOTICE: Works Only On ACU 6 or ACU 7 Boards",
    "partNumber": "210290954",
    "image": "/products/lcd-7inch-sunviewable-gt3000.png",
    "inStock": true
  },
  {
    "id": 32,
    "sku": "OSO-00032",
    "name": "Genmega T4000 LCD Upgrade Kit, AA104SH02",
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 983.00,
    "price": 1100.00,
    "description": "T4000 LCD Upgrade Kit",
    "partNumber": "210290944",
    "image": "/products/lcd-aa104sh02-t4000.png",
    "inStock": true
  },
  {
    "id": 33,
    "sku": "OSO-00033",
    "name": "Genmega 2 High HPCDU, Without Cassettes",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1584.00,
    "price": 1800.00,
    "description": "2 High 4K HPCDU, Without Cassettes NOTICE: Does Not Include Shutter Module",
    "partNumber": "151110591",
    "image": "/products/151110591.jpg",
    "inStock": true
  },
  {
    "id": 34,
    "sku": "OSO-00034",
    "name": "Genmega GT5000 2 High PCDU II, With Presenter, Without Cassettes",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 2130.00,
    "price": 2300.00,
    "description": "GT5000 2 High 4K PCDU II, With Presenter, Without Cassettes",
    "partNumber": "151112711",
    "image": "/products/cdu-2high-pcdu2-presenter.png",
    "inStock": true
  },
  {
    "id": 35,
    "sku": "OSO-00035",
    "name": "Genmega 2 High SCDU-E III, Without Cassettes",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 973.00,
    "price": 1100.00,
    "description": "2 High 2K SCDU-E III, Without Cassettes NOTICE: Standard SCDU Cassettes Will NOT Fit",
    "partNumber": "151130221",
    "image": "/products/151130221.jpg",
    "inStock": true
  },
  {
    "id": 36,
    "sku": "OSO-00036",
    "name": "Genmega 3 High HCDU, Without Cassettes",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1584.00,
    "price": 1750.00,
    "description": "3 High 6K HCDU, Without Cassettes",
    "partNumber": "151110461",
    "image": "/products/cdu-3high-hcdu-front-load.png",
    "inStock": true
  },
  {
    "id": 37,
    "sku": "OSO-00037",
    "name": "Genmega 3 High Feed Module Upgrade, Without Cassettes",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1070.00,
    "price": 1200.00,
    "description": "3 High Feed Module Upgrade, Turns HCDU Into 4 High 8K",
    "partNumber": "151120531",
    "image": "/products/151120531.jpg",
    "inStock": true
  },
  {
    "id": 38,
    "sku": "OSO-00038",
    "name": "Genmega CDU Control Board, Blue, HCDU",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 327.00,
    "price": 380.00,
    "description": "CDU Control Board, Blue, HCDU",
    "partNumber": "151210481",
    "image": "/products/cdu-control-board-blue-hcdu.png",
    "inStock": true
  },
  {
    "id": 39,
    "sku": "OSO-00039",
    "name": "Genmega 1-High HCDU, Without Cassette",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1037.00,
    "price": 1200.00,
    "description": "1-High 2K HCDU, Without Cassette",
    "partNumber": "151110441",
    "image": "/products/151110441.jpg",
    "inStock": true
  },
  {
    "id": 40,
    "sku": "OSO-00040",
    "name": "Genmega 1-High HPCDU, Without Cassette",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1365.00,
    "price": 1500.00,
    "description": "1-High 2K HPCDU, Without Cassette",
    "partNumber": "151110571",
    "image": "/products/151110571.jpg",
    "inStock": true
  },
  {
    "id": 41,
    "sku": "OSO-00041",
    "name": "Genmega SCDU-E III 2nd Feed Module Upgrade, Without Cassette",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 218.00,
    "price": 300.00,
    "description": "Second Feed Module For SCDU-E III NOTICE: Will Not Work On Standard SCDU",
    "partNumber": "151119981",
    "image": "/products/151119981.jpg",
    "inStock": true
  },
  {
    "id": 42,
    "sku": "OSO-00042",
    "name": "Genmega 1-High SCDU-E III, Without Cassette",
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 754.00,
    "price": 850.00,
    "description": "Genmega 1-high 1K SCDU-E III CDU NOTICE: SCDU-E Can Be Upgraded To 2 High",
    "partNumber": "151130211",
    "image": "/products/151130211.jpg",
    "inStock": true
  },
  {
    "id": 43,
    "sku": "OSO-00043",
    "name": "Genmega 2\" WRPU, ONYX-W Printer",
    "manufacturer": "Genmega",
    "category": "Printers",
    "cost": 491.00,
    "price": 582.00,
    "description": "2\" WRPU, ONYX-W Printer",
    "partNumber": "271110151",
    "image": "/products/271110151.jpg",
    "inStock": true
  },
  {
    "id": 44,
    "sku": "OSO-00044",
    "name": "Genmega G3000 Onyx Top Bezel",
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 131.00,
    "price": 180.00,
    "description": "G3000 Onyx Top Bezel",
    "partNumber": "120219751",
    "image": "/products/120219751.jpg",
    "inStock": true
  },
  {
    "id": 45,
    "sku": "OSO-00045",
    "name": "Genmega G3000 Onyx LCD Bezel",
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 131.00,
    "price": 180.00,
    "description": "G3000 Onyx LCD Bezel",
    "partNumber": "120219771",
    "image": "/products/120219771.jpg",
    "inStock": true
  },
  {
    "id": 46,
    "sku": "OSO-00046",
    "name": "Genmega Nova Door Bezel, Without LED",
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 142.00,
    "price": 185.00,
    "description": "Nova Door Bezel, Without LED",
    "partNumber": "120219641",
    "image": "/products/120219641.png",
    "inStock": true
  },
  {
    "id": 47,
    "sku": "OSO-00047",
    "name": "Genmega G2500 Door Bezel",
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 109.00,
    "price": 140.00,
    "description": "G2500 Door Bezel",
    "partNumber": "120219651",
    "image": "/products/120219651.jpg",
    "inStock": true
  },
  {
    "id": 48,
    "sku": "OSO-00048",
    "name": "Genmega Nova Top Bezel, With Touchscreen, Without MCR EPP Bezel",
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 431.00,
    "price": 500.00,
    "description": "Nova Top Bezel, With Touchscreen, Without MCR EPP Bezel",
    "partNumber": "120104751",
    "image": "/products/120104751.png",
    "inStock": true
  },
  {
    "id": 49,
    "sku": "OSO-00049",
    "name": "Genmega 1700W Door Bezel",
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 121.00,
    "price": 160.00,
    "description": "1700W Door Bezel",
    "partNumber": "120104611",
    "image": "/products/120104611.jpg",
    "inStock": true
  },
  {
    "id": 50,
    "sku": "OSO-00050",
    "name": "Genmega 1700W Top Bezel",
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 162.00,
    "price": 200.00,
    "description": "1700W Top Bezel",
    "partNumber": "120104441",
    "image": "/products/120104441.jpg",
    "inStock": true
  },
  {
    "id": 51,
    "sku": "OSO-00051",
    "name": "Genmega WCDU-2K Cassette",
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "WCDU-2K Cassette",
    "partNumber": "141170011",
    "image": "/products/141170011.jpg",
    "inStock": true
  },
  {
    "id": 52,
    "sku": "OSO-00052",
    "name": "Genmega 2K Note Cassette, 3rd",
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "3rd Cassette, MCDU/HCDU/HPCDU/PCDU/RCDU",
    "partNumber": "141139521",
    "image": "/products/141139521.png",
    "inStock": true
  },
  {
    "id": 53,
    "sku": "OSO-00053",
    "name": "Genmega 2K Note Cassette, 4th",
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "4th Cassette, MCDU/HCDU/HPCDU/PCDU/RCDU",
    "partNumber": "141139531",
    "image": "/products/141139531.png",
    "inStock": true
  },
  {
    "id": 54,
    "sku": "OSO-00054",
    "name": "Genmega SCDU-E Cassette, 1st",
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 334.00,
    "price": 450.00,
    "description": "SCDU-E Cassette, 1st NOTICE: Will Not Work With Standard SCDU",
    "partNumber": "141170101",
    "image": "/products/141170101.jpg",
    "inStock": true
  },
  {
    "id": 55,
    "sku": "OSO-00055",
    "name": "Genmega SCDU-E Cassette, 2nd",
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 334.00,
    "price": 450.00,
    "description": "SCDU-E Cassette, 2nd NOTICE: Will Not Work With Standard SCDU",
    "partNumber": "141170111",
    "image": "/products/141170111.jpg",
    "inStock": true
  },
  {
    "id": 56,
    "sku": "OSO-00056",
    "name": "Genmega 8\" LCD Panel, G2500",
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 284.00,
    "price": 320.00,
    "description": "8\" LCD Panel, G2500 NOTICE: Does Not Include Ribbon Cable",
    "partNumber": "210207711",
    "image": "/products/210207711.jpg",
    "inStock": true
  },
  {
    "id": 57,
    "sku": "OSO-00057",
    "name": "Genmega 7\" LCD Panel, 1700W, G1900, GT3000",
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 251.00,
    "price": 290.00,
    "description": "7\" LCD Panel, 1700W, G1900, GT3000 NOTICE: Does Not Include Ribbon Cable",
    "partNumber": "210207701",
    "image": "/products/210207701.jpg",
    "inStock": true
  },
  {
    "id": 58,
    "sku": "OSO-00058",
    "name": "Genmega GT3000 7\" LCD Assembly",
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 349.00,
    "price": 390.00,
    "description": "GT3000 LCD With Bezel, Function Keys, Cables",
    "partNumber": "210107551",
    "image": "/products/210107551.jpg",
    "inStock": true
  },
  {
    "id": 59,
    "sku": "OSO-00059",
    "name": "Genmega 1700W 7\" LCD Assembly",
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 349.00,
    "price": 390.00,
    "description": "1700W LCD With Bezel, Function Keys, Cables",
    "partNumber": "210107541",
    "image": "/products/210107541.jpg",
    "inStock": true
  }
];

export const categories = [
  "All Parts","Cassettes","Dispensers","Printers","Keypads","Card Readers",
  "Power Supplies","LCD Displays","Locks","Bezels","Upgrade Kits",
  "Keys & Accessories","Wireless/Connectivity","Mainboards","Components","Toppers"
];

export const manufacturers = ["All","Genmega","Hyosung","InHand","Origin","Universal"];

export const repairCategories = [
  "All Services","CDU / Dispenser","Cassette","Note Separator",
  "Keypad / EPP","Power Supply","Printer","Card Reader","Mainboard","Combo Deals"
];

export const repairServices = [
  {"id":1,"name":"Repair of 1K/2K CDU, Hyosung","manufacturer":"Hyosung","category":"CDU / Dispenser","price":199,"originalPrice":249.99,"description":"Full diagnostics, cleaning, belt/roller service, and bench testing for 1K/2K cash dispensers."},
  {"id":2,"name":"Repair of 4K CDU w/o Cassettes, Hyosung","manufacturer":"Hyosung","category":"CDU / Dispenser","price":299.99,"description":"4K dispenser unit repair, cassettes not included. Includes full function test."},
  {"id":3,"name":"Repair of Dual 1K CDU, Hyosung","manufacturer":"Hyosung","category":"CDU / Dispenser","price":299.99,"description":"Dual 1K dispenser repair with complete recalibration and testing."},
  {"id":4,"name":"Repair of Drawer CDU, Hyosung","manufacturer":"Hyosung","category":"CDU / Dispenser","price":244.99,"description":"Drawer-style CDU repair including transport path and sensor service."},
  {"id":5,"name":"Repair of TCDU CDU, Hantle/Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":249.99,"description":"TCDU dispenser repair for Hantle/Genmega units."},
  {"id":6,"name":"Repair of HCDU/RCDU 4K/6K CDU, Hantle/Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":299.99,"description":"High-capacity 4K/6K HCDU/RCDU dispenser repair."},
  {"id":7,"name":"Repair of Dual SCDU CDU, Hantle/Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":299.99,"description":"Dual SCDU dispenser repair and calibration."},
  {"id":8,"name":"Repair of SCDU CDU, Hantle/Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":249.99,"description":"Single SCDU dispenser repair with full bench test."},
  {"id":9,"name":"Repair of WCDU Dispenser, Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":249.99,"description":"WCDU dispenser repair for Genmega units."},
  {"id":10,"name":"Repair of MCDU-HCDU-RCDU 1K/2K Note Dispenser, Hantle/Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":249.99,"description":"MCDU/HCDU/RCDU 1K/2K note dispenser repair."},
  {"id":11,"name":"Repair of 1K/2K Cassette, Hyosung","manufacturer":"Hyosung","category":"Cassette","price":169.99,"description":"Cassette repair including pusher plate, springs, and gate service."},
  {"id":12,"name":"Repair of SDD 1700 Cassette","manufacturer":"Genmega","category":"Cassette","price":139.99,"description":"SDD 1700 cassette repair and reconditioning."},
  {"id":13,"name":"Repair of Cassette for SCDU, Hantle/Genmega","manufacturer":"Genmega","category":"Cassette","price":157.99,"description":"SCDU cassette repair for Hantle/Genmega units."},
  {"id":14,"name":"Repair of Cassette for HCDU/RCDU/MCDU, Hantle/Genmega","manufacturer":"Genmega","category":"Cassette","price":157.99,"description":"HCDU/RCDU/MCDU cassette repair and reconditioning."},
  {"id":15,"name":"Repair of Drawer Note Separator, Hyosung","manufacturer":"Hyosung","category":"Note Separator","price":144.99,"description":"Note separator repair for drawer-style dispensers."},
  {"id":16,"name":"Repair of Cassette Note Separator, Hyosung 1K/2K/3K","manufacturer":"Hyosung","category":"Note Separator","price":169.99,"description":"Note separator repair for 1K/2K/3K cassettes."},
  {"id":17,"name":"Repair of B1/B2/B3/B5 Keypad/EPP, Hantle/Genmega","manufacturer":"Genmega","category":"Keypad / EPP","price":174.99,"description":"EPP keypad repair for Hantle/Genmega B-series units."},
  {"id":18,"name":"Repair of PCI 5.0 EPP X1, Hyosung","manufacturer":"Hyosung","category":"Keypad / EPP","price":234.99,"description":"PCI 5.0 EPP X1 encrypting pin pad repair."},
  {"id":19,"name":"Repair of PCI 3.0 EPP 8000R, Hyosung","manufacturer":"Hyosung","category":"Keypad / EPP","price":234.99,"description":"PCI 3.0 EPP 8000R encrypting pin pad repair."},
  {"id":20,"name":"Repair of Power Supply, Hyosung","manufacturer":"Hyosung","category":"Power Supply","price":169.99,"description":"Standard Hyosung power supply repair and load test."},
  {"id":21,"name":"Repair of 5000/7000 Series Power Supply, Hyosung","manufacturer":"Hyosung","category":"Power Supply","price":274.99,"description":"High-output 5000/7000 series power supply repair."},
  {"id":22,"name":"Repair of Power Supply, Genmega/Hantle","manufacturer":"Genmega","category":"Power Supply","price":149.99,"description":"Genmega/Hantle power supply repair and load test."},
  {"id":23,"name":"Repair of Printer, Hyosung","manufacturer":"Hyosung","category":"Printer","price":124.99,"description":"Receipt printer repair, head cleaning, and feed adjustment."},
  {"id":24,"name":"Repair of EMV Card Reader, Hyosung","manufacturer":"Hyosung","category":"Card Reader","price":145.99,"description":"EMV card reader repair and read-head service."},
  {"id":25,"name":"Repair of Main Board, Win6/Win7","manufacturer":"Hyosung","category":"Mainboard","price":124.99,"description":"Win6/Win7 mainboard diagnostics and component-level repair."},
  {"id":26,"name":"COMBO: 1K/2K CDU + Cassette Repair, Hyosung","manufacturer":"Hyosung","category":"Combo Deals","price":398.98,"isCombo":true,"description":"Bundle: 1K/2K CDU repair plus cassette repair at a combined rate."},
  {"id":27,"name":"COMBO: 4K CDU w/2 Cassettes Repair, Hyosung","manufacturer":"Hyosung","category":"Combo Deals","price":569.97,"isCombo":true,"description":"Bundle: 4K CDU repair plus two cassette repairs."},
  {"id":28,"name":"COMBO: Talaris SDD 1700 Dispenser w/Cassette Repair","manufacturer":"Genmega","category":"Combo Deals","price":346.73,"isCombo":true,"description":"Bundle: SDD 1700 dispenser repair plus cassette repair."},
  {"id":29,"name":"COMBO: MCDU-HCDU-RCDU-SCDU CDU + Cassette, Hantle/Genmega","manufacturer":"Genmega","category":"Combo Deals","price":389.48,"isCombo":true,"description":"Bundle: Hantle/Genmega CDU repair plus cassette repair."}
];

export function hasRealImage(product) {
  return !!product.image && !product.image.includes('placeholder');
}
