// app/lib/products.js - Complete product database for OSO ATM Parts

export const products = [
  {
    "id": 1,
    "sku": "OSO-00001",
    "name": "Genmega ACU 7 Mainboard",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "Mainboards",
    "cost": 600.00,
    "price": 700.00,
    "description": "CE, Main Board, ACU 7, Without Modem",
    "partNumber": "161110881",
    "image": "/products/acu7-mainboard.png",
    "inStock": true
  },
  {
    "id": 2,
    "sku": "OSO-00002",
    "name": "Genmega RCDU, Rear Load Dispenser, Without Cassette",
    "weight": 30.0,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1037.00,
    "price": 1300.00,
    "description": "1-High, 2K RCDU, Rear Load Dispenser, Without Cassette",
    "partNumber": "151107931",
    "image": "/products/rcdu-rear-load-dispenser.png",
    "inStock": true
  },
  {
    "id": 3,
    "sku": "OSO-00003",
    "name": "Genmega NFC Card Reader",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "Card Readers",
    "cost": 180.00,
    "price": 300.00,
    "description": "Genmega NFC/TAP VIVOPAY Card Reader NOTICE: Comes With Wire Harness & Install Template",
    "partNumber": "180102381",
    "image": "/products/nfc-card-reader.png",
    "inStock": true
  },
  {
    "id": 4,
    "sku": "OSO-00004",
    "name": "Genmega 2K Note Cassette, 1st",
    "weight": 10.0,
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "1st Cassette, MCDU/HCDU/HPCDU/PCDU/RCDU",
    "partNumber": "141139501",
    "image": "/products/hcdu-2k-cassette.png",
    "inStock": true
  },
  {
    "id": 5,
    "sku": "OSO-00005",
    "name": "Genmega Mini High Bright Topper",
    "weight": 15.0,
    "manufacturer": "Genmega",
    "category": "Toppers",
    "cost": 119.00,
    "price": 160.00,
    "description": "Mini HB Topper II",
    "partNumber": "110189141",
    "image": "/products/mini-high-bright-topper.png",
    "inStock": true
  },
  {
    "id": 6,
    "sku": "OSO-00006",
    "name": "S&G Electronic Lock",
    "weight": 1.5,
    "manufacturer": "Hyosung & Genmega",
    "category": "Locks",
    "cost": 92.00,
    "price": 110.00,
    "description": "Electronic Lock With Keypad",
    "partNumber": "231114341",
    "image": "/products/sg-electronic-lock.png",
    "inStock": true
  },
  {
    "id": 7,
    "sku": "OSO-00007",
    "name": "Genmega SCDU / WCDU 1K Cassette",
    "weight": 10.0,
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 334.00,
    "price": 400.00,
    "description": "1K Cassette NOTICE: Will Not Work With SCDU-E 2 High",
    "partNumber": "141170001",
    "image": "/products/scdu-wcdu-1k-cassette.png",
    "inStock": true
  },
  {
    "id": 8,
    "sku": "OSO-00008",
    "name": "Genmega SCDU Dispenser, Without Cassette",
    "weight": 30.0,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 741.00,
    "price": 850.00,
    "description": "1K Dispenser Without Cassette",
    "partNumber": "151119851",
    "image": "/products/scdu-1k-dispenser.png",
    "inStock": true
  },
  {
    "id": 9,
    "sku": "OSO-00009",
    "name": "Genmega 2\" Printer Assembly",
    "weight": 5.5,
    "manufacturer": "Genmega",
    "category": "Printers",
    "cost": 491.00,
    "price": 600.00,
    "description": "2\" Printer Assembly Without Image Print",
    "partNumber": "271110101",
    "image": "/products/printer-2inch-assembly.png",
    "inStock": true
  },
  {
    "id": 10,
    "sku": "OSO-00010",
    "name": "Genmega 2 High HCDU, Without Cassettes",
    "weight": 40.0,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1116.00,
    "price": 1300.00,
    "description": "2 High, 4K HCDU Without Cassettes",
    "partNumber": "151110451",
    "image": "/products/hcdu-2high.png",
    "inStock": true
  },
  {
    "id": 11,
    "sku": "OSO-00011",
    "name": "Genmega / Hantle Power Supply",
    "weight": 5.5,
    "manufacturer": "Genmega",
    "category": "Power Supplies",
    "cost": 294.00,
    "price": 350.00,
    "description": "Genmega Power Supply",
    "partNumber": "251118791",
    "image": "/products/power-supply.png",
    "inStock": true
  },
  {
    "id": 12,
    "sku": "OSO-00012",
    "name": "Hyosung Bezel Key",
    "weight": 1.5,
    "manufacturer": "Hyosung",
    "category": "Keys & Accessories",
    "cost": 6.00,
    "price": 9.00,
    "description": "Fits All Hyosung Model Types",
    "partNumber": "45110110",
    "image": "/products/HyoKey.png",
    "inStock": false
  },
  {
    "id": 13,
    "sku": "OSO-00013",
    "name": "ATM Wireless Antenna",
    "weight": 1.5,
    "manufacturer": "Universal",
    "category": "Wireless/Connectivity",
    "cost": 5.00,
    "price": 12.00,
    "description": "Standard Antenna - Increases Cellular Reception",
    "image": "/products/StandardAntenna.png",
    "inStock": true
  },
  {
    "id": 14,
    "sku": "OSO-00014",
    "name": "Hyosung Printer Assembly",
    "weight": 5.5,
    "manufacturer": "Hyosung",
    "category": "Printers",
    "cost": 719.99,
    "price": 683.99,
    "description": "Hyosung Receipt Printer Assembly",
    "image": "/products/placeholder.png",
    "inStock": false
  },
  {
    "id": 15,
    "sku": "OSO-00015",
    "name": "Hyosung Power Supply",
    "weight": 5.5,
    "manufacturer": "Hyosung",
    "category": "Power Supplies",
    "cost": 347.99,
    "price": 330.99,
    "description": "New Revision Power Supply",
    "image": "/products/placeholder.png",
    "inStock": false
  },
  {
    "id": 16,
    "sku": "OSO-00016",
    "name": "Hyosung EMV Card Reader",
    "weight": 1.5,
    "manufacturer": "Hyosung",
    "category": "Card Readers",
    "cost": 289.99,
    "price": 274.99,
    "description": "Card Reader Only. NOTICE: Not An Upgrade Kit",
    "image": "/products/placeholder.png",
    "inStock": false
  },
  {
    "id": 17,
    "sku": "OSO-00017",
    "name": "Hyosung LCD Display Panel with LED Backlight",
    "weight": 1.5,
    "manufacturer": "Hyosung",
    "category": "LCD Displays",
    "cost": 275.99,
    "price": 261.99,
    "description": "New Revision 10.1\" LCD Display Panel Without Electronics",
    "image": "/products/placeholder.png",
    "inStock": false
  },
  {
    "id": 18,
    "sku": "OSO-00018",
    "name": "Hyosung NFC Reader Complete Kit For Halo II",
    "weight": 1.5,
    "manufacturer": "Hyosung",
    "category": "Card Readers",
    "cost": 379.99,
    "price": 360.99,
    "description": "NFC Reader Kit For Halo II",
    "image": "/products/placeholder.png",
    "inStock": true
  },
  {
    "id": 21,
    "sku": "OSO-00021",
    "name": "InHand I-22 4G Wireless Router",
    "weight": 3.5,
    "manufacturer": "InHand",
    "category": "Wireless/Connectivity",
    "cost": 100.00,
    "price": 130.00,
    "description": "InHand I-22 4G LTE Router For ATM. NOTICE: Purchase Outright",
"variants": [
  { "label": "AT&T", "monthlyFee": 7 },
  { "label": "Verizon", "monthlyFee": 7 },
  { "label": "Dual (AT&T/Verizon)", "monthlyFee": 12 }
],
    "image": "/products/Inhand.png",
    "inStock": true
  },
  {
    "id": 26,
    "sku": "OSO-00026",
    "name": "Origin Wireless Router",
    "weight": 3.5,
    "manufacturer": "Origin",
    "category": "Wireless/Connectivity",
    "cost": 80.00,
    "price": 100.00,
    "description": "Origin Wireless Router For ATM. NOTICE: Purchase Outright",
    "variants": [
  { "label": "AT&T", "monthlyFee": 7 },
  { "label": "Verizon", "monthlyFee": 7 },
  { "label": "Dual (AT&T/Verizon)", "monthlyFee": 12 }
],
    "image": "/products/OriginWireless.png",
    "inStock": true
  },
  {
    "id": 27,
    "sku": "OSO-00027",
    "name": "Genmega Bezel Key, Type C415A, Two Keys",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "Locks",
    "cost": 7.00,
    "price": 9.00,
    "description": "Genmega Bezel Key, Not For Nova or Kiosk",
    "partNumber": "230210581",
    "image": "/products/c415a-key.png",
    "inStock": true
  },
  {
    "id": 28,
    "sku": "OSO-00028",
    "name": "Genmega Barrel Key, Eagle, 1 Key",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "Locks",
    "cost": 6.00,
    "price": 9.00,
    "description": "Genmega Barrel Key, Eagle, 1 Key",
    "partNumber": "230200591",
    "image": "/products/eagle-barrel-key.png",
    "inStock": true
  },
  {
    "id": 29,
    "sku": "OSO-00029",
    "name": "Genmega Keypad, PCI V5.X Certified, EPP B5",
    "weight": 3.5,
    "manufacturer": "Genmega",
    "category": "Keypads",
    "cost": 437.00,
    "price": 550.00,
    "description": "EPP, PCI V5.X CERTIFIED, EPP B5. NOTICE: This Keypad Requires ATM Software Version V05.00.37 Or Higher",
    "partNumber": "201207541",
    "image": "/products/201207541.png",
    "inStock": true
  },
  {
    "id": 30,
    "sku": "OSO-00030",
    "name": "Gengmega EMV Card Reader, Type TDR",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "Card Readers",
    "cost": 218.00,
    "price": 250.00,
    "description": "EMV Card Reader, Type TDR-R240N. NOTICE: This Is The Card Reader Only - No Cable Or Bracket Included",
    "partNumber": "241180071",
    "image": "/products/241180071.jpg",
    "inStock": true
  },
  {
    "id": 31,
    "sku": "OSO-00031",
    "name": "Genmega GT3000 LCD Upgrade Kit, Sunviewable 7\" LCD",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 710.00,
    "price": 850.00,
    "description": "Upgrade Kit, Sunviewable 7\" LCD, GT3000 NOTICE: Works Only On ACU 6 or ACU 7 Boards",
    "partNumber": "210290954",
    "image": "/products/lcd-7inch-sunviewable-gt3000.png",
    "inStock": true
  },
  {
    "id": 32,
    "sku": "OSO-00032",
    "name": "Genmega T4000 LCD Upgrade Kit, AA104SH02",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 983.00,
    "price": 1100.00,
    "description": "T4000 LCD Upgrade Kit",
    "partNumber": "210290944",
    "image": "/products/lcd-aa104sh02-t4000.png",
    "inStock": true
  },
  {
    "id": 33,
    "sku": "OSO-00033",
    "name": "Genmega 2 High HPCDU, Without Cassettes",
    "weight": 40.0,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1584.00,
    "price": 1800.00,
    "description": "2 High 4K HPCDU, Without Cassettes NOTICE: Does Not Include Shutter Module",
    "partNumber": "151110591",
    "image": "/products/151110591.jpg",
    "inStock": true
  },
  {
    "id": 34,
    "sku": "OSO-00034",
    "name": "Genmega GT5000 2 High PCDU II, With Presenter, Without Cassettes",
    "weight": 40.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 2130.00,
    "price": 2300.00,
    "description": "GT5000 2 High 4K PCDU II, With Presenter, Without Cassettes",
    "partNumber": "151112711",
    "image": "/products/cdu-2high-pcdu2-presenter.png",
    "inStock": true
  },
  {
    "id": 35,
    "sku": "OSO-00035",
    "name": "Genmega 2 High SCDU-E III, Without Cassettes",
    "weight": 30.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 973.00,
    "price": 1100.00,
    "description": "2 High 2K SCDU-E III, Without Cassettes NOTICE: Standard SCDU Cassettes Will NOT Fit",
    "partNumber": "151130221",
    "image": "/products/151130221.jpg",
    "inStock": true
  },
  {
    "id": 36,
    "sku": "OSO-00036",
    "name": "Genmega 3 High HCDU, Without Cassettes",
    "weight": 50.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1584.00,
    "price": 1750.00,
    "description": "3 High 6K HCDU, Without Cassettes",
    "partNumber": "151110461",
    "image": "/products/cdu-3high-hcdu-front-load.png",
    "inStock": true
  },
  {
    "id": 37,
    "sku": "OSO-00037",
    "name": "Genmega 3 High Feed Module Upgrade, Without Cassettes",
    "weight": 50.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1070.00,
    "price": 1200.00,
    "description": "3 High Feed Module Upgrade, Turns HCDU Into 4 High 8K",
    "partNumber": "151120531",
    "image": "/products/151120531.jpg",
    "inStock": true
  },
  {
    "id": 38,
    "sku": "OSO-00038",
    "name": "Genmega CDU Control Board, Blue, HCDU",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 327.00,
    "price": 380.00,
    "description": "CDU Control Board, Blue, HCDU",
    "partNumber": "151210481",
    "image": "/products/cdu-control-board-blue-hcdu.png",
    "inStock": true
  },
  {
    "id": 39,
    "sku": "OSO-00039",
    "name": "Genmega 1-High HCDU, Without Cassette",
    "weight": 30.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1037.00,
    "price": 1200.00,
    "description": "1-High 2K HCDU, Without Cassette",
    "partNumber": "151110441",
    "image": "/products/151110441.jpg",
    "inStock": true
  },
  {
    "id": 40,
    "sku": "OSO-00040",
    "name": "Genmega 1-High HPCDU, Without Cassette",
    "weight": 35.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 1365.00,
    "price": 1500.00,
    "description": "1-High 2K HPCDU, Without Cassette",
    "partNumber": "151110571",
    "image": "/products/151110571.jpg",
    "inStock": true
  },
  {
    "id": 41,
    "sku": "OSO-00041",
    "name": "Genmega SCDU-E III 2nd Feed Module Upgrade, Without Cassette",
    "weight": 20.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 218.00,
    "price": 300.00,
    "description": "Second Feed Module For SCDU-E III NOTICE: Will Not Work On Standard SCDU",
    "partNumber": "151119981",
    "image": "/products/151119981.jpg",
    "inStock": true
  },
  {
    "id": 42,
    "sku": "OSO-00042",
    "name": "Genmega 1-High SCDU-E III, Without Cassette",
    "weight": 30.5,
    "manufacturer": "Genmega",
    "category": "Dispensers",
    "cost": 754.00,
    "price": 850.00,
    "description": "Genmega 1-high 1K SCDU-E III CDU NOTICE: SCDU-E Can Be Upgraded To 2 High",
    "partNumber": "151130211",
    "image": "/products/151130211.jpg",
    "inStock": true
  },
  {
    "id": 43,
    "sku": "OSO-00043",
    "name": "Genmega 2\" WRPU, ONYX-W Printer",
    "weight": 5.5,
    "manufacturer": "Genmega",
    "category": "Printers",
    "cost": 491.00,
    "price": 582.00,
    "description": "2\" WRPU, ONYX-W Printer",
    "partNumber": "271110151",
    "image": "/products/271110151.jpg",
    "inStock": true
  },
  {
    "id": 44,
    "sku": "OSO-00044",
    "name": "Genmega G3000 Onyx Top Bezel",
    "weight": 15.5,
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 131.00,
    "price": 180.00,
    "description": "G3000 Onyx Top Bezel",
    "partNumber": "120219751",
    "image": "/products/120219751.jpg",
    "inStock": true
  },
  {
    "id": 45,
    "sku": "OSO-00045",
    "name": "Genmega G3000 Onyx LCD Bezel",
    "weight": 5.5,
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 131.00,
    "price": 180.00,
    "description": "G3000 Onyx LCD Bezel",
    "partNumber": "120219771",
    "image": "/products/120219771.jpg",
    "inStock": true
  },
  {
    "id": 46,
    "sku": "OSO-00046",
    "name": "Genmega Nova Door Bezel, Without LED",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 142.00,
    "price": 185.00,
    "description": "Nova Door Bezel, Without LED",
    "partNumber": "120219641",
    "image": "/products/120219641.png",
    "inStock": true
  },
  {
    "id": 47,
    "sku": "OSO-00047",
    "name": "Genmega G2500 Door Bezel",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 109.00,
    "price": 140.00,
    "description": "G2500 Door Bezel",
    "partNumber": "120219651",
    "image": "/products/120219651.jpg",
    "inStock": true
  },
  {
    "id": 48,
    "sku": "OSO-00048",
    "name": "Genmega Nova Top Bezel, With Touchscreen, Without MCR EPP Bezel",
    "weight": 15.5,
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 431.00,
    "price": 500.00,
    "description": "Nova Top Bezel, With Touchscreen, Without MCR EPP Bezel",
    "partNumber": "120104751",
    "image": "/products/120104751.png",
    "inStock": true
  },
  {
    "id": 49,
    "sku": "OSO-00049",
    "name": "Genmega 1700W Door Bezel",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 121.00,
    "price": 160.00,
    "description": "1700W Door Bezel",
    "partNumber": "120104611",
    "image": "/products/120104611.jpg",
    "inStock": true
  },
  {
    "id": 50,
    "sku": "OSO-00050",
    "name": "Genmega 1700W Top Bezel",
    "weight": 15.5,
    "manufacturer": "Genmega",
    "category": "Bezels",
    "cost": 162.00,
    "price": 200.00,
    "description": "1700W Top Bezel",
    "partNumber": "120104441",
    "image": "/products/120104441.jpg",
    "inStock": true
  },
  {
    "id": 51,
    "sku": "OSO-00051",
    "name": "Genmega WCDU-2K Cassette",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "WCDU-2K Cassette",
    "partNumber": "141170011",
    "image": "/products/141170011.jpg",
    "inStock": true
  },
  {
    "id": 52,
    "sku": "OSO-00052",
    "name": "Genmega 2K Note Cassette, 3rd",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "3rd Cassette, MCDU/HCDU/HPCDU/PCDU/RCDU",
    "partNumber": "141139521",
    "image": "/products/141139521.png",
    "inStock": true
  },
  {
    "id": 53,
    "sku": "OSO-00053",
    "name": "Genmega 2K Note Cassette, 4th",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 534.00,
    "price": 650.00,
    "description": "4th Cassette, MCDU/HCDU/HPCDU/PCDU/RCDU",
    "partNumber": "141139531",
    "image": "/products/141139531.png",
    "inStock": true
  },
  {
    "id": 54,
    "sku": "OSO-00054",
    "name": "Genmega SCDU-E Cassette, 1st",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 334.00,
    "price": 450.00,
    "description": "SCDU-E Cassette, 1st NOTICE: Will Not Work With Standard SCDU",
    "partNumber": "141170101",
    "image": "/products/141170101.jpg",
    "inStock": true
  },
  {
    "id": 55,
    "sku": "OSO-00055",
    "name": "Genmega SCDU-E Cassette, 2nd",
    "weight": 10.5,
    "manufacturer": "Genmega",
    "category": "Cassettes",
    "cost": 334.00,
    "price": 450.00,
    "description": "SCDU-E Cassette, 2nd NOTICE: Will Not Work With Standard SCDU",
    "partNumber": "141170111",
    "image": "/products/141170111.jpg",
    "inStock": true
  },
  {
    "id": 56,
    "sku": "OSO-00056",
    "name": "Genmega 8\" LCD Panel, G2500",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 284.00,
    "price": 320.00,
    "description": "8\" LCD Panel, G2500 NOTICE: Does Not Include Ribbon Cable",
    "partNumber": "210207711",
    "image": "/products/210207711.jpg",
    "inStock": true
  },
  {
    "id": 57,
    "sku": "OSO-00057",
    "name": "Genmega 7\" LCD Panel, 1700W, G1900, GT3000",
    "weight": 1.5,
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 251.00,
    "price": 290.00,
    "description": "7\" LCD Panel, 1700W, G1900, GT3000 NOTICE: Does Not Include Ribbon Cable",
    "partNumber": "210207701",
    "image": "/products/210207701.jpg",
    "inStock": true
  },
  {
    "id": 58,
    "sku": "OSO-00058",
    "name": "Genmega GT3000 7\" LCD Assembly",
    "weight": 5.5,
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 349.00,
    "price": 390.00,
    "description": "GT3000 LCD With Bezel, Function Keys, Cables",
    "partNumber": "210107551",
    "image": "/products/210107551.jpg",
    "inStock": true
  },
  {
    "id": 59,
    "sku": "OSO-00059",
    "name": "Genmega 1700W 7\" LCD Assembly",
    "weight": 5.5,
    "manufacturer": "Genmega",
    "category": "LCD Displays",
    "cost": 349.00,
    "price": 390.00,
    "description": "1700W LCD With Bezel, Function Keys, Cables",
    "partNumber": "210107541",
    "image": "/products/210107541.jpg",
    "inStock": true
   },
  {
  "id": 60,
  "sku": "OSO-00060",
  "name": "Gengmega EMV Card Reader Kit, Type TDR",
  "weight": 1.5,
  "manufacturer": "Genmega",
  "category": "Card Readers",
  "cost": 262.00,
  "price": 290.00,
  "description": "EMV Card Reader, Bracket, And Cable. Type TDR-R240N. NOTICE: Select Machine Type",
  "partNumber": "281215504, 281215514, 281215524, 281215534, 281215544, 281215554, 281215564, 281215574, 281215584, 281215594",
  "image": "/products/EMVupgrade.png",
  "inStock": true,
  "options": [
    {
      "name": "ATM Type",
      "values": ["1700W", "G1900", "G2500", "T4000", "GT5000", "C6000", "G6000", "Onyx", "GT3000", "Kiosk"]
    }
  ]
}
];

export const categories = [
  "All Parts","Cassettes","Dispensers","Printers","Keypads","Card Readers",
  "Power Supplies","LCD Displays","Locks","Bezels","Upgrade Kits",
  "Keys & Accessories","Wireless/Connectivity","Mainboards","Components","Toppers"
];

export const manufacturers = ["All","Genmega","Hyosung","InHand","Origin","Universal"];

export const repairCategories = [
  "All Services","CDU / Dispenser","Cassette",
  "Keypad / EPP","Printer",
];

export const repairServices = [
  {"id":1,"name":"Repair of 1K/2K/4K/6K/8K CDU, Hyosung","manufacturer":"Hyosung","category":"CDU / Dispenser","price":250.00,"description":"Full Diagnostics, Cleaning, Repair, And Bench Testing"},
  {"id":2,"name":"Repair of Drawer CDU, Hyosung","manufacturer":"Hyosung","category":"CDU / Dispenser","price":250.00,"description":"Drawer-Style Dispenser Repair And Bench Testing"},
  {"id":3,"name":"Repair of TCDU CDU, Hantle/Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":250.00,"description":"TCDU Dispenser Repair And Bench Testing"},
  {"id":4,"name":"Repair of 1K/2K/4K/6K/8K CDU, Hantle/Genmega","manufacturer":"Genmega","category":"CDU / Dispenser","price":250.00,"description":"Full Diagnostics, Cleaning, Repair, And Bench Testing"},
  {"id":5,"name":"Repair of 1K/2K Cassette, Hyosung","manufacturer":"Hyosung","category":"Cassette","price":150.00,"description":"Cassette Repair Including Cleaning And Bench Testing"},
  {"id":6,"name":"Repair of 1K/2K Cassette, Hantle/Genmega","manufacturer":"Genmega","category":"Cassette","price":150.00,"description":"Cassette Repair Including Cleaning And Bench Testing"},
  {"id":7,"name":"Repair of Drawer Note Separator, Hyosung","manufacturer":"Hyosung","category":"Note Separator","price":150.00,"description":"Note Separator Repair For Drawer-Style Dispensers"},
  {"id":8,"name":"Repair of B1/B2/B3/B5 Keypad/EPP, Hantle/Genmega","manufacturer":"Genmega","category":"Keypad / EPP","price":160.00,"description":"EPP Keypad Repair For Hantle/Genmega B-series units"},
  {"id":9,"name":"Repair of PCI 5.0 EPP X1, Hyosung","manufacturer":"Hyosung","category":"Keypad / EPP","price":200.00,"description":"PCI 5.0 EPP X1 Keypad Repair"},
  {"id":10,"name":"Repair of PCI 3.0 EPP 8000R, Hyosung","manufacturer":"Hyosung","category":"Keypad / EPP","price":200.00,"description":"PCI 3.0 EPP 8000R Keypad Repair"},
  {"id":11,"name":"Repair of Printer, Hyosung","manufacturer":"Hyosung","category":"Printer","price":160.00,"description":"Receipt Printer Repair"},
  {"id":12,"name":"Repair of Printer, Hantle/Genmega","manufacturer":"Genmega","category":"Printer","price":160.00,"description":"Receipt Printer Repair"},
];

export function hasRealImage(product) {
  return !!product.image && !product.image.includes('placeholder');
}
